### ISSUE TITLE
Use rebase for feature branches

### ISSUE THREAD

**Issue by shadowhand** [git-town/git-town#1156]
Right now it looks that `git town sync` will **always** merge the development branch into feature branches. Our workflow mandates that all feature branches need to be *rebased* on the development branch. In git terms, this means:

```shell
git checkout develop
git pull
git checkout feature-branch
git rebase develop
git push --force-with-lease
```

It would be nice to have a config option like [pull-branch-strategy](https://github.com/Originate/git-town/blob/master/documentation/commands/pull-branch-strategy.md) for `feature-branch-strategy`:

```shell
git town feature-branch-strategy <merge|rebase>
```

**Comment by charlierudolph** [comment]
Rebasing a feature branch that has been pushed up requires a force push. Are you okay with that?

**Comment by shadowhand** [comment]
So long as `git push --force-with-lease` is used, yes.

**Comment by charlierudolph** [comment]
Woah, didn’t know that option existed. This is fine by me. @kevgo what do you think?

**Comment by kevgo** [comment]
Yeah, implementing this using `--force-with-lease` sounds more secure. I like it!

**Comment by iamandrewluca** [comment]
And if `--force-with-lease` fails, it stops, and can ask to execute something like
```bash
git town continue merge # fallback strategy
# or
git town continue force # force push
```

**Comment by iamandrewluca** [comment]
Or maybe we have something like eg: `git town pull-branch-strategy`

### SYNOPSIS
```
git town sync-strategy [(merge | rebase)]
```
Default value will be `merge`.  No breaking changes
When `rebase` is used, will use `--force-with-lease` to push
If was rejected, we can give options to
* abort
* push force

Or if we don't want to use force, we should first rebase from origin then from main branch

**Comment by iamandrewluca** [comment]
Temporary or maybe permanent solution :)
```bash
alias towns='git-town sync && git rebase $(git config git-town.main-branch-name)'
```

**Comment by sheldonhull** [comment]
First issue I actually went looking for
Since a feature branch in my environment is specific to a developer, not shared, having the option to rebase on latest from master, then apply my commit means I eliminate 1 extra commit from the feature branch timeline, resulting in a cleaner history. 

![image](https://user-images.githubusercontent.com/3526320/73773780-6707c000-4748-11ea-8300-8b36a3dbed78.png)

This example shows what would happen in 3 steps might be reduced to two. I would like to request a global config setting I could use to ensure my pull request and branch strategy are able to be default to rebase workflow. 

In the case of a shared branch, this would need to change of course.

**Comment by iamandrewluca** [comment]
@sheldonhull try alias I recommended above, I use it almost half a year and it works very well.
