### ISSUE TITLE
refactor for more unit tests

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#1177]
### Primary goal

I want to reduce our number of feature tests by being able to test the edge cases with unit tests.

I would mainly like to add unit tests for building the step list for each command where we mock out the functions that tell us what state the repository is in. We could optionally also execute the step list by mocking the running of commands and validate that the steps run the expected git commands.

### Potential Solution

I would like to refactor the codebase so instead of files exposing methods, they instead expose services which implement interfaces. Services are then injected into other services and we can unit test them by mocking the service interfaces. There are a variety of tools for generating mocks for a given interface. We can also use https://github.com/uber-go/dig for creating the actual instances.

### Branch with POC

I got the `git append` feature to pass on my branch [cr-services](https://github.com/Originate/git-town/compare/cr-services?expand=1). 

Notes:
* The two top level services are a step list builder (I extracted the code from a cmd files) and the step runner. 
  * The step list builder gets all the service injected, accepts args / flags as input and outputs the step list. 
  * The step runner gets all the services injected and passes them to the step when calling their methods.
* I mainly added files and only changed the steps to allow injection (this allowed it to build without changing everything). The other features currently fail.
* Each file got turned into a service, that implemented an interface. The implementations are private and only the interface and constructor are public.
* I moved a few functions around in order to allow the services to depend on each other without cycles
* I did not convert the drivers injectable services yet

### Additional items to discuss

* If we agree on this, do we merge in one big swoop or find a way to break up the conversion?

@kevgo thoughts?

**Comment by kevgo** [comment]
Thanks for taking this on @charlierudolph, and sorry for the delayed response, I am doing a lot of business travel these days. In general, I support the idea of adding more unit tests in order to balance out the testing pyramid. 

I am, however, not excited about adding so much complexity and abstraction - both to the production as well as the test architecture - just to enable unit testing of something for which we already have good, expressive, stable, and relatively speedy Cucumber tests. Our entire test suite runs in under 5 minutes, which isn't that bad. I see us at most shaving off a minute or two here, which is not enough justification for more complexity in my opinion.

The existing Git Town architecture is already complex enough, which is a deterrent for external contributions. I got that feedback repeatedly from people who wanted to contribute and had a hard time wrapping their heads around the command pattern we use. If we add service interfaces, dependency injection, and test mocks, this problem will compound and make Git Town less rather than more maintainable in my opinion.

An interesting reference that I think applies here is DHH's [TDD is dead](http://david.heinemeierhansson.com/2014/tdd-is-dead-long-live-testing.html) blog post, as well as the (very thoughtful and recommended to watch) [video series](https://www.youtube.com/watch?v=z9quxZsLcfo) where he discusses this idea with the inventors of TDD (Kent Beck, Martin Fowler). The TLDR is that testing is great, but it has side effects, which can exceed its value if its principles TDD (for example the testing pyramid) are followed too rigidly. 

As an alternative approach to reduce CI test times, we could switch over to CircleCI and run the various tests (linter, unit tests, end-to-end tests) in parallel. I am doing that on [Text-Runner](https://github.com/originate/text-runner), see image below:

![image](https://user-images.githubusercontent.com/268934/46900128-42107f00-ce6b-11e8-9a66-7314e140bf27.png)

It would easily translate to Git-Town. I think I can bring down the test time to 2 minutes this way, without any additional architectural complexity. What do you think?

**Comment by kevgo** [comment]
@charlierudolph I keep thinking about this. The overall goal (having more unit tests) is worthwhile. So is the separation of business logic into a services layer. I just want to limit the amount of complexity that get's added to the architecture in order to achieve this. 

How would the unit tests look like? Do we even need to (want to) mock dependencies? Mocking makes tests run in a test bubble that can easily deviate from reality. If yes to mocking, which parts do you plan on mocking, and how would the mocks be used? I think adding a few example unit tests would help visualize the motivation for this refactor.

I am currently working on converting the end-to-end tests from Ruby to Go. If we had infrastructure to set up Git workspaces in Go, could we write the unit tests without mocking?

To avoid passing the `StepDependencies` around everywhere, can we make them a global variable? I think global state is fine for configuration values that are read only by production code. Tests could swap out attributes of this global variable for mocked versions.

I'm not sure we need the dependency injection framework. It does a bit too much magic for my taste.

**Comment by charlierudolph** [comment]
The primary thing I want to unit test is building the step list for each command given the variety of states.

We could certainly test that while still calling git under the hood, and the only thing we would need to configure is what is the working directory the git commands are called in.

**Comment by charlierudolph** [comment]
Unit tests should probably also mock out prompts

**Comment by kevgo** [comment]
Sounds good.

**Comment by kevgo** [comment]
Update on this: The business logic to generate step lists is now 100% unit testable without any additional interfaces, mock implementations, or other test-related infrastructure!

I have refactored the code that generates step lists into pure logic and thereby testable solely through input data. A unit test for the step generator logic just needs to provide the data that the imperative shell of Git Town would have loaded from the Git repo to the function that generates step lists from this information, and then verify the generated step list.

The logic to load the configuration data from the environment is separately testable if that's needed. I consider it simple and typechecked/linted enough to have a low probability for bugs, so I think coverage through the end-to-end tests is enough here.

Given the large surface area of Git Town, I still have a hard time seeing how such smaller-scale tests of subcomponents replace any end-to-end tests. The unit tests need to make too many assumptions about the rest of the system to act as the sole verification that Git Town handles exotic Git setups properly. End-to-end tests still add substantial confidence on top of such unit tests and therefore still seem necessary.

Btw the entire end-to-end test suite now runs in 20 sec(!) when using Asahi Linux on Apple Silicon. It's typically faster to run all e2e tests than to create the call that runs a single unit tests! The e2e suite takes 40 sec on Linux on my 5 year old Intel laptop.

Given that many of the original design goals stated in this ticket are achieved, and I consider the remaining ones not desirable, I'll go ahead and close this ticket for the time being to keep the list of issues actionable. Feel free to comment or reopen at any time!
