### ISSUE TITLE
Add option to never push on sync

### ISSUE THREAD

**Issue by grignaak** [git-town/git-town#1181]
My company frowns upon pushing features to `origin` which is default behavior of `git town sync` (we have a different remote for in-progress feature branches). I tend to work with git town in offline mode almost exclusively; doing a `git fetch` before each `git town sync`.

It would be nice there were an option to **never create a remote feature branch** *OR* an option to specify a **different feature remote**. The first option seems more natural to me.

Either of these options would also fix #1180 for me.

**Comment by kevgo** [comment]
Not pushing feature branches to a remove at all would go against the philosophy of Git Town, which is to help secure the development workflow. It would incur a risk of losing work when the local machine is compromised. That feels like too much rope for devs to hang themselves with.

I could imagine a configuration setting like `feature-branch-remote` that specifies a different remote for feature branches. @grignaak can you please outline why your company doesn't push feature branches to `origin` so that we can better understand this request?

**Comment by grignaak** [comment]
Believe it or not, we have a different remote for in-progress feature branches.

**Comment by koppor** [comment]
> I could imagine a configuration setting like `feature-branch-remote` that specifies a different remote for feature branches. @grignaak can you please outline why your company doesn't push feature branches to `origin` so that we can better understand this request?

Here, it is on a case-by-case bases.

The normal "origin" is https://github.com/JabRef/jabref/.

However, there are branches, which are a) experimental or b) will take months to complete. We collect these branches at https://github.com/koppor/jabref/pulls to keep the list at the original repository rather small. It's "just" psychology, but i) newcomers  have a fear of large numbers, ii) having the goal to push the numbers of opened PRs below 10 is some kind of motivation we use, and iii) seeing the list of PRs fitting on one page is really motivating.

**Comment by kevgo** [comment]
@koppor thanks for the background. I get the best practice to only have PRs that are ready for review in the "official" repo. What you described should be possible with the normal workflow around forked repositories:

1. You clone the https://github.com/koppor/jabref repo onto your machine.
2. Set a Git remote called `upstream` to `git@github.com:JabRef/jabref.git` for this clone on your machine:

       git remote add upstream git@github.com:JabRef/jabref.git
3. Git Town now syncs the branches in https://github.com/koppor/jabref with the `main` branch in that repo AND with the main branch in https://github.com/JabRef/jabref. See https://www.git-town.com/preferences/sync-upstream.html for more info.
4. You can select into which repository new pull requests go (`JabRef/jabref` or `koppor/jabref`) in the dialog that pops up when running `git new-pull-request`.

**Comment by koppor** [comment]
@kevgo Thank you for the hint! I renamed the remotes accordingly! Now, it also "feels better" when doing how-tos for newcomers.

`git-town` now tries to sync with `origin/main` instead of `upstream/main`.

Even though "main" is configured as `upstream`

```toml
[branch "main"]
	remote = upstream
	merge = refs/heads/main
```

![image](https://user-images.githubusercontent.com/1366654/229992344-3f0c0ee5-b288-4e74-a859-f57d0703978d.png)

Does git-town need a separate configuration for the `main` branch?

**Comment by koppor** [comment]
Maybe, I should open another issue...

As a side-note "git rebase" does not work, whereas git pull works:

(OK, `git rebase` seemed to use `origin`, but i should have used `upstream`)

![image](https://user-images.githubusercontent.com/1366654/230001014-b793f529-5e0d-410f-9192-e2ff755bc773.png)

**Comment by kevgo** [comment]
What do you think about this setup for your use case? It would be fully supported by the existing functionality and be pretty "idiomatic":

- https://github.com/koppor/jabref is a fork of https://github.com/JabRef/jabref.
- Development happens completely in https://github.com/koppor/jabref. Branches in this this repo get synced with the `main` branch in this repo, i.e. with `origin/main`. This is necessary to make the pull requests in https://github.com/koppor/jabref/pulls display the right changes.
- When a branch is under development it has a PR in https://github.com/koppor/jabref/pulls. When a branch is ready to be merged, you make another PR into https://github.com/JabRef/jabref.

The forked repo becomes outdated when PRs get merged into https://github.com/JabRef/jabref. To fix this, you need to sync the forked repo. You can sync the fork with the facilities that [GitHub provides](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) or let Git Town do it for you as part of `git sync`.

If you want Git Town to sync your fork, add (as previously described) a Git remote called `upstream` that points to the original repo. Don't change the existing `origin` remote. When you run `git sync`, Git Town first pulls new commits from https://github.com/JabRef/jabref (`upstream/main`) into the main branch in https://github.com/koppor/jabref (`origin/main`). Then it syncs the feature branch with `origin/main`. Now everything is up to date.

If you set things up this way, when you run `git remote -v` in the forked repo, you should see something like this:

```
origin    git@github.com:koppor/jabref.git (fetch)
origin    git@github.com:koppor/jabref.git (push)
upstream  git@github.com:JabRef/jabref.git (fetch)
upstream  git@github.com:JabRef/jabref.git (push)
```

You can find more infos around working with forks at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks.

**Comment by koppor** [comment]
Thank you for the explanation. I could copy that into our [teaching material](https://devdocs.jabref.org/teaching.html).

I think, the secret was to configure main as follows:

```toml
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

And not `upstream` as I did in https://github.com/git-town/git-town/issues/1181#issuecomment-1496954317

Maybe, `git-town` could spit out a warning, if users start to configure their branches with `upsteam`?

**Comment by kevgo** [comment]
> Maybe, git-town could spit out a warning, if users start to configure their branches with upsteam?

Good idea, possibly as part of https://github.com/git-town/git-town/issues/2215.

**Comment by amarpatel** [comment]
An option that says "Do you want to push?" after `git sync` would be ideal.  I'd like full control over what and when I'm pushing.  Helping a friend on their branch, running `git sync`, and seeing that I rebased it accidentally is no fun.

**Comment by kevgo** [comment]
@amarpatel your use-case sounds like a one-off situation. So maybe a CLI switch `git sync --no-push` might be a better fit for your use case. I'm concerned that a configuration option will lead to prompts on every run of `git sync`, and this prompt will become annoying over time in 99.9% of the use cases. And if the user doesn't make a choice, the `git sync` command would just hang and not finish. 

>  Helping a friend on their branch, running git sync, and seeing that I rebased it accidentally is no fun.

Can you please describe what exactly the problem is in this situation? If Git Town rebases a feature branch, either your friend or you configured Git Town to rebase feature branches. If different configurations on different developer machines are a problem in your environment, would a [Git Town configuration file](https://github.com/git-town/git-town/issues/1030) be a solution for you?

**Comment by kevgo** [comment]
@amarpatel Git Town now provides first-class support for your use case: https://www.git-town.com/advanced-syncing. Please check it out!

**Comment by kevgo** [comment]
Consolidating all requests to not push on sync into #2715 because that ticket provides motivation that applies to the most Git Town users.

The issue of having a separate remote for in-progress feature branches feels rooted in a non-idiomatic repo setup. A more idiomatic setup was proposed in this ticket: fork the production codebase, clone that fork, develop feature branches in that fork, and make proposals from the fork into the original repo. Git Town provides full support for this setup out of the box.

If an organization needs further support for their specific custom repo situation, I'm available as a consultant/freelancer to help either improve your code hosting setup and developer experience, or add support for such client-specific features to Git Town.

**Comment by kevgo** [comment]
A dedicated config setting for disabling all pushes is now available as part of [Git Town 22](https://github.com/git-town/git-town/releases/tag/v22.0.0).
