### ISSUE TITLE
Please respect TERM=dumb

### ISSUE THREAD

**Issue by zenspider** [git-town/git-town#1201]
I haven't looked into the code too much yet (not a go coder (yet?)) but the menuing on `git town config setup` (or when auto-invoked) expects full VT-xx/xterm support, which is not available when TERM=dumb or TERM=emacs (for example). Either `os.GetEnv("TERM")` should be queried and decisions made based on that or actual term capability should be queried.

If you point me in the right direction, I can do a (possibly fake) PR with the idea behind it.

**Comment by kevgo** [comment]
Hey @zenspider! There are two elements of Git Town output that could cause problems here:

1. formatting branches in bold text: I think we enforce color at all times because our end-to-end tests need to see them. We never had issues with this setup, but I can see an adjustment if needed, i.e. add configuration to omit colors.
2. complex UI when configuring Git Town: we use https://github.com/AlecAivazis/survey in this case. The only alternative I can think of is providing command-line switches for the config variables. We had that in the past but decided that a nice terminal UI is nicer. 

Can you get the Git Town configuration done in a "real" terminal outside of Emacs? If that's a problem, please share a screenshot of the broken output.

**Comment by zenspider** [comment]
The bold codes are stripped by emacs (in my config, not by default).

The main problem is #2, that menu picker thing. I would think defaulting to plain string reads would be fine, no? (easy for the branching question, not as easy but still doable for the perennials question).

**Comment by zenspider** [comment]
I'm also happy to file the same ticket on the survey project and link back to here if you'd rather delegate it off instead of work around.

**Comment by kevgo** [comment]
Yeah, I think this is an upstream issue. Git Town is just a user of survey. I didn't find any configuration options around fallback to simpler input on dumber terminals in their documentation. So this seems a survey issue.

**Comment by zenspider** [comment]
It _can be_ an upstream issue. It can also be applied here by detecting TERM and using plain IO reads. Since upstream hasn't even responded in 2 months, I'm guessing any traction will have to be here.

**Comment by zenspider** [comment]
I walked away when the maintainers punted... Nice idea, bad UX.

**Comment by kevgo** [comment]
Apologies for a misconfigured stale-bot closing this when it totally shouldn't have.
