### ISSUE TITLE
Running 'new-pull-request' on master automatically pushes code to origin/master

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1342]
I made a mistake and believed that I was working on a feature branch. However, I was actually working on `master`. When I went to create a PR, my copy of the branch was automatically pushed to master. Normally, our users are prevented from pushing directly to master via protected branches. However, as an admin, I'm able to push directly to master.

It might be interesting to consider having `git-town` check to see if it's pushing to `origin/master` before attempting to create a new pull request.

**Comment by kevgo** [comment]
Hi @cirego, thanks for the experience report! This happens to me all the time as well! 😆  

You describe clientside branch protection. I think all branch protection should happen on the server since that's the only place where it is effective. If one wants to enforce this on the client, I would implement this on the Git level, for example as a [pre-push hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). This way, all pushes are covered: manual `git push`, pushes from `git ship`, `git sync`, `git hack`, `git new-pull-request` et al, as well as pushes from other clients like the Git clients in IDEs or bash scripts. 

I ended up configuring the Git server to block admins (including myself) from pushing to master. Most of the time, I shouldn't use this superpower anyways. It's better if I make pull requests that go through the CI server like everybody else. In the very few situations where I need to push directly to master in emergencies, I can always disable the feature on the server, do the changes I need to do, and re-enable it. This is similar to how sysadmins are not sudo all the time on servers. They run with normal user privileges most of the time, but can run `sudo` for individual commands that need escalated privileges.

**Comment by cirego** [comment]
Hi @kevgo, thanks for the quick reply! I totally agree that the proper way to fix this is server-side.

I filed this issue to see if it's worth discussing whether or not this behavior is surprising and/or unwanted. As a user, I would like `git town new-pull-request` to fail if it's going to push directly to one of my `main` or `perennial` branches. Especially since the PR on GitHub will be empty because there is no diff to display.

It also might be worth considering just to improve the error message in the even that `git push` fails due to branch protections.

As for the server settings, I'm planning to do exactly what you described, since I do tend to footgun myself on this one.

**Comment by kevgo** [comment]
I agree that the use case you describe is surprising and unwanted behavior. But it would be even more surprising and unwanted if somebody makes the effort to configure Git Town to not push to perennial branches, and then can run `git push` on the command line to do exactly that. 

If Git Town starts making any sort of promise of branch protection, it must provide a good, dependable solution. But it can't do that because it doesn't control the local Git client nor the Git server. Hence, Git Town stays intentionally out of this question and leaves branch protection up to a system that can solve this problem: the Git server and maybe the Git client. Git Town focuses on playing well with such solutions while providing a good answer to keeping feature branches in sync. 

[Here](https://ghost.org/changelog/prevent-master-push) is an example of a pre-push hook that should solve your problem in a better way than Git Town can. I haven't tested it. Does that work for you?

**Comment by kevgo** [comment]
https://github.com/git-town/git-town/issues/2224 tracks the implementation of this idea. I'm closing this ticket as a duplicate. Please add additional comments in the linked issue.
