### ISSUE TITLE
Support rebase strategy for `sync` and `new-pull-request`

### ISSUE THREAD

**Issue by aeneasr** [git-town/git-town#1383]
GitHub now allows us to require a linear history which prevents merge commits from being pushed to matching branches:

<img width="784" alt="Bildschirmfoto 2020-05-07 um 11 51 15" src="https://user-images.githubusercontent.com/3372410/81280745-35f59f00-9059-11ea-8dbc-acc050205f03.png">

Because of the way `git sync` works, we end up with merge commits in between our commits if the main dev branch had updates. This in turn can cause the "rebase" merge option on GitHub to not be available. I believe this happens when merge conflicts have been resolved. 

This then conflicts with the linear commit history dictated by the branch protection rule, leaving only "Squash & Rebase" as a viable merge strategy which destroys our beautiful commit messages!

Therefore, I would like to be able to tell git-town to use `git pull --rebase` (or whatever it is doing under the hood) instead of `git pull` when doing `git-town sync`

More context:

- https://help.github.com/en/github/administering-a-repository/requiring-a-linear-commit-history
- https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-merges

**Comment by cirego** [comment]
I too would also like to see an option for using `rebase` instead of `merge` to keep my branch history linear.

**Comment by kevgo** [comment]
I'm not against doing this. Just out of curiosity, why don't you do do `Squash and merge`? That's the most idiot-proof option in my experience (for people like me) and what Git Town recommends in order to maintain a linear history on long-lived branches. It allows you to commit frequently on feature branches, take detours, move fast and break things, swear in commit messages, merge as often as you want, and when shipping the feature branch, all this gets collapsed into one beautiful linear commit that looks perfect and has a thoughtfully crafted commit message.

If I look at some of your PRs ([this](https://github.com/ory/hydra/pull/1446/commits) or [this](https://github.com/ory/hydra/pull/1570/commits) or [this](https://github.com/ory/hydra/pull/1846/commits)), do you really want all these commits in your `master` branch?

**Comment by aeneasr** [comment]
For all examples there are counter examples (https://github.com/ory/kratos/pull/388, https://github.com/ory/kratos/pull/392) and rebase pull is a core (and loved) git strategy. Sure, there are other tools to help with the flow but why not support it natively and follow best practices documented on GitHub? I guess writing my own git alias for this is easy as pie but it would be much nicer if this came out of the box!

For the linked PRs, those are community contributed and people typically lack skill and experience in writing good commit messages that follow a common project language. But they're also typically not Git-Town users (yet ;) )!

For me, as a heavy superuser, this would be very useful. I don't really care about other's PRs ;)

**Comment by kevgo** [comment]
Git Town's primary purpose is to maximize the total throughput of an engineering team (hence the name "town"). From that perspective, a rebase strategy has many disadvantages:

1. It limits collaboration. Since rebases rewrite history, a feature branch that is being synced via rebases cannot be shared between developers anymore. This means no more collaboration on features.
2. It undermines Git's persistence guarantees and increases the risk of data loss: when everybody is constantly undoing and redoing all the commits they already finished, it's just a question of time until somebody loses already committed changes. It's a numbers game, and the numbers are large in large teams. It is safer to leave existing commits the way they are and commit updates on top of them. 
3. It is brittle. It stops working if anybody does a git merge.
4. It exposes large groups of people to unnecessary technical complexity and a steeper learning curve. Now everybody has to learn to do open-heart surgery on their Git commits.
5. It leads to more merge conflicts since you have to re-apply every merge conflict resolution to potentially every commit in your branch.
6. A feature branch whose commits are important makes multiple independent changes. Such branches live longer and accumulate more changes, leading to more merge conflicts for you. Some changes are already done but are not getting shipped, leading to more merge conflicts for others later. 
7. 99.9999% (six nines) of the time this will lead to temporary garbage commits making it into the main code line, polluting the Git history.

Anytime a team tells me "we chose to sync our branches with rebases" my answer is "you shouldn't do that". Often these policies have been created by the superheroes on the team who can do rebases in their sleep. But 99% of the work is done by "normal" people because there aren't enough superheroes. Teams should optimize the setup to make the overall group productive, and avoid adding too much rope for people to hang themselves with. Superheroes are there to help in exceptional situations.

Having said all this, there are exceptions to every rule, and any town is better off if it has a few super-heroes living in it. Your example of making a larger change efficiently as a series of smaller changes in a branch, where the build is broken in between but it doesn't matter because all of this gets shipped after 2 days as a whole, is convincing. The world is a better place if such sweeping changes are possible.

A solution could be to allow rebases for individual contributors but leave the default as squash-merges. This setting would have to be applied consistently, i.e. also to `git ship`, otherwise it is pointless.

Guidance for implementing this:
- add a `syncStrategy` setting to [getSyncConfig](https://github.com/git-town/git-town/blob/master/src/cmd/sync.go#L67)
- change [getSyncFeatureBranchSteps](https://github.com/git-town/git-town/blob/master/src/steps/sync_steps.go#L38-L44) to run a [RebaseBranchStep](https://github.com/git-town/git-town/blob/master/src/steps/rebase_branch_step.go) instead of a `MergeBranchStep` when the `syncStrategy` configuration flag is set to `rebase`.
- add end-to-end tests in the [features](https://github.com/git-town/git-town/tree/master/features) folder

**Comment by kevgo** [comment]
@blaggacao in #1452: 

> In a scenario, where I use eg. [commitizen](http://commitizen.github.io/cz-cli) to produce valid, structured and well auditable git history
> I'd like to opt out to squashing the commits on shipping
> in order to preserve the inherent value of a well formatted git history.

**Comment by blaggacao** [comment]
I think for my use case it would fit perfectly to just _not_ squash the commits when merging.
I can craft telling merge commit resume with my commitizen approach and let auditors choose to expand on the details.

**Comment by blaggacao** [comment]
Here is how it can be done, saving best of both worlds:

**Use Case 1**
- I want to retarget a child branch onto main branch
- because _it turned out_ to be a loosely coupled feature
- and can be shipped independently off the spot

**Currently**
- I can't retarget without dragging the parent branch history
- Doing proper merge conflict repare at a few commits distance from the originating commit is... hilarious, especially if the intent splits, like when retargeting (splitting a tree)

**Heaven & Hell**
Rebase is great for such flexibility, **on the other hand** it breaks state of the world (or "town").
See discussion at #1383 

# Suggestion
```feature
Feature: syncing preserving clean history

  As a developer, on a complex feature
  I want to be able to reshuffel history
  So that I can use it as en effective (linear) brain extension during development.

  As a reviewer of a bigger feature, on the final non-WIP PR
  I want to be able to trace milestones of the developer's though process
  I don't want to see the whole journey
  I want to see an opimized & clarified version of it
  I want to consume proficient storytelling off the commit history
  So that I can review logical sub-units of the feature increment

  Scenario: running "git town sync" with rebase strategy
    Given my repo has a main branch named "main"
    And has a parent feature branch named "parent"
    And has a current feature branch named "feature"
    And has a child feature branch named "child"
    And the following commits exist in my repo
      | BRANCH  | LOCATION      | COMMIT | PARENTCOMMIT |
      | parent  | local  remote | p/A    | --           |
      | parent  |        remote | p/B    | p/A          |
      | feature | local  remote | f/A    | p/B          |
      | child   | local  remote | c/A    | f/A          |

    And I am working on branch "feature"
    When I run "git-town sync", after resolving conflicts
    Then the following commits exist
      | BRANCH  | LOCATION      | COMMIT | PARENTCOMMIT |
      | parent  | local  remote | p/A    | --           |
      | parent  | local  remote | p/B    | p/A          |
      | feature |        remote | f/A    | p/B          |
      | feature | local         | f/A'   | p/B          |
      | feature | local  remote | f/Am   | f/A' /  f/A  |
      | child   |        remote | c/A    | f/A          |
      | child   | local         | c/A'   | f/A'         |
      | child   | local  remote | c/Am   | c/A' /  c/A  |

  Scenario: running "git town ship" with rebase strategy
    Given I was working on branch "feature"
    Then the followin commits exists
      | BRANCH  | LOCATION      | COMMIT | PARENTCOMMIT |
      | parent  | local  remote | p/A    | --           |
      | parent  | local  remote | p/B    | p/A          |
      | feature | local  remote | f/A'   | p/B          |
      | feature | local  remote | f/Am   | f/A'         |
      | child   | local  remote | c/Am   | c/A'         |

```

**Comment by blaggacao** [comment]
Reading again  carefully over the above suggestion, given the underlying assumptions are met and this is technically feasible, although advanced, then I understand that this workflow might result superior to either pure version of `merge` or `rebase`. So much so that it might become a default candidate.

**Comment by kevgo** [comment]
@blaggacao can you please outline which Git commands the various Git Town commands should run in your example? Does it still do a rebase when syncing and a rebase when shipping?

**Comment by blaggacao** [comment]
I'm leaving out flags / using pseudo commands, to communicate the basic idea, only
```
git fetch
git checkout f/A
git rebase remote/origin/p/B  # produces f/Am'
git checkout remote/origin/p/B  # Headless here
git merge f/A # produces f/Am, headless too
git push f/Am  # in a way that remote/origin/p references it (don't know how)
git checkout f/Am'
git merge f/Am
```

**Comment by blaggacao** [comment]
What good for? Most importantly:

- It limits _intermittent_ side effects on my private series of _linear_ commits on my working branch
- Any merges only reflect my **difference in opinion** as to conflict reconciliation between remote's opinion and my own. They **never** reflect independent changes. That's a powerful sanity check.

**Comment by blaggacao** [comment]
## Start

Errata: `master` -> `remote/feature`

![image](https://user-images.githubusercontent.com/7548295/83720582-efb34180-a5fe-11ea-94d1-fab3743124e3.png)

## After Syncing (twice)

Errata: `remote` -> `remote/feature`

1. sync
2. make progress 3b
3. sync again

- remote only sees one additional merge over `Some Update` (hopefully empty) + additional commits which are fast forwarded with (the graphing tool didn't support --no-commit`)
![image](https://user-images.githubusercontent.com/7548295/83722497-b4b30d00-a602-11ea-841c-83ddabcd1a0b.png)

**Comment by kevgo** [comment]
Guidance for implementation:

- go to file [sync-steps.go](https://github.com/git-town/git-town/blob/main/src/steps/sync_steps.go)
- look at how [getSyncNonFeatureBranchSteps](https://github.com/git-town/git-town/blob/main/src/steps/sync_steps.go#L61) checks the pull-branch-strategy and depending on it's setting appends either a `RebaseBranchStep` or a `MergeBranchStep`
- apply the same logic to `getSyncFeatureBranchSteps` in that file

**Comment by kevgo** [comment]
Additional motivation for this: https://github.blog/2022-06-30-write-better-commits-build-better-projects

**Comment by kevgo** [comment]
Git Town [7.9](https://github.com/git-town/git-town/releases/tag/v7.9.0) now allows updating feature branches through rebasing.

**Comment by aeneasr** [comment]
🔥
