### ISSUE TITLE
brew installed version of git-town does not have version info

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#1413]
When installing git-town via brew, the version info is missing. Version info is correct when downloading the binary.

![Screen Shot 2020-05-13 at 9 11 32 AM](https://user-images.githubusercontent.com/1676758/81837528-d7696e80-94f9-11ea-8f62-716a72edcc4b.png)

**Comment by charlierudolph** [comment]
Here is our formula for brew: https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-town.rb

**Comment by kevgo** [comment]
Rather than fixing this in our old process, let's try #1379 and see if it will fix this.

**Comment by kevgo** [comment]
The issue seems that our formula [points only to the source code](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-town.rb#L4) and Homebrew then [builds the binary](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-town.rb#L21) without the compiler flags to set the variables. Fixing in https://github.com/Homebrew/homebrew-core/pull/57491.

**Comment by charlierudolph** [comment]
Thanks for fixing @kevgo! Just pulled in the latest from homebrew and it has the version info!
