### ISSUE TITLE
Add gitea support

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1451]
gitea is a highly popular git server written in go, which looks very similar to github.

**Comment by kevgo** [comment]
Agree! Since the maintainers don't have access to Gitea, this is something that should come from the community.

Guidance for implementation:
- follow the structure of the other code hosting drivers in https://github.com/git-town/git-town/tree/master/src/drivers

**Comment by blaggacao** [comment]
note to future self (or other): https://gitea.com/gitea/go-sdk

**Comment by blaggacao** [comment]
must fix #1164 on the go

**Comment by blaggacao** [comment]
@kevgo What's the (guaranteed) expected shape of the string returned by `MergePullRequest(MergePullRequestOptions) (string, error)` ? It wouldn't be too bad to replace those string interfaces with well-defined structs...

**Comment by kevgo** [comment]
Wow, cool that Gitea provides a Go SDK to talk to their API! This makes creating support for Gitea super easy. Just follow the structure of the [GitHub driver](https://github.com/git-town/git-town/blob/master/src/drivers/github.go), it uses a Go SDK for the Github API.

The `MergePullRequest` method returns the SHA of the commit created by the merge. See [the implementation](https://github.com/git-town/git-town/blob/master/src/drivers/github.go#L161) for details. It picks the `sha` field from the [response](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button) provided by GitHub. [Here](https://github.com/git-town/git-town/blob/master/src/steps/driver_merge_pull_request_step.go#L71) is where the result is used.

You are right that returning naked strings feels a bit "stringly typed". Git Town uses structs to structure data where possible. An example is the input ([MergePullRequestOptions](https://github.com/git-town/git-town/blob/master/src/drivers/github.go#L57)) to the method mentioned above. The return value of this method, however, is a single string. Creating a struct to contain just a single string feels like overkill since all it does is add a name for the string variable. I'll address your concern by adding names for the return variable. Thanks for helping improve Git Town!

**Comment by kevgo** [comment]
I have created #1456 to add names to return values.

**Comment by blaggacao** [comment]
Yeah, indeed it's relatively straight forward, however, there is [one "hard" problem](https://github.com/git-town/git-town/blob/63a65fa148d4cf6ab783bb68e9533bd5936fca7a/src/drivers/gitea.go#L196), I hope this is bearable.

**Comment by kevgo** [comment]
Hopefully Gitea adds this to their API soon! Fortunately, this only occurs for edge cases like when working with nested feature branches. Most people should never encounter this problem. 

Good progress on the Gitea driver implementation btw!

**Comment by blaggacao** [comment]
Implemented in https://github.com/git-town/git-town/pull/1518
