### ISSUE TITLE
git town config sqash-on-ship

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1452]
In a scenario, where I use eg. [`commitizen`](http://commitizen.github.io/cz-cli/) to produce valid, structured and well auditable git history, I'd like to opt out to squashing the commits on shipping, in order to preserve the inherent value of a well formatted git history.

**Comment by kevgo** [comment]
Hi @blaggacao! I think what you are asking for is to do `git town sync` using rebase, and `git town ship` via a rebase as well. If this is true, this request is similar to #1383. Please see the discussion there for background on why Git Town doesn't support this feature as of now (but might in the future). Since this is a duplicate, I'm closing this ticket. Let's continue the discussion on the #1383 ticket. If you disagree, feel free to re-open this issue. Thanks!  🙂
