### ISSUE TITLE
keep state on pullrequests

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1453]
https://github.com/git-town/git-town/blob/be335a327681068ff8315df01988b91335e4c53c/src/steps/driver_merge_pull_request_step.go#L71

by here, we should have state from the local config about the pull-request ID, else we unwieldy query the pullrequestlist api pager.

spotted while working on #1451

**Comment by blaggacao** [comment]
I see why this is difficult, after handing off to the browser...

**Comment by blaggacao** [comment]
Looks like at least since the call to `CanMergePullRequest`, we could be smart enough to derive the actual pull request's identity from this API's call, so we avoid another round trip and simplify code a little.

https://github.com/git-town/git-town/blob/be335a327681068ff8315df01988b91335e4c53c/src/cmd/ship.go#L165-L177

**Comment by kevgo** [comment]
You are right that we already have the pull request number in [CanMergePullRequest](https://github.com/git-town/git-town/blob/master/src/drivers/github.go#L30-L43) and store it so that we don't need to do another API call to get the same pull request number in [mergePullRequest](https://github.com/git-town/git-town/blob/master/src/drivers/github.go#L141-L144). @charlierudolph do you remember why we don't cache the pull request number?

**Comment by charlierudolph** [comment]
Can't think of any reason we would need the separate calls. Thanks for the clean up.
