### ISSUE TITLE
Custom commit command fot `git town ship`

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1532]
When sqash-shipping a _speed programmed_ branch with insidious commit history, I'd like to get help of a commitizen script which helps me interactively craft a changelog-ready commit message, so that, in master, the history can be readily paresed to generate a conventional change log.

In my case, the command is: `cz commit`, but it should probably allow arbitrary shell commands like: `pre-commit run test && cz commit`

**Comment by blaggacao** [comment]
Related to #1529 #1383 

This issue proposes to get from:
```
-o--o-- master
  \
   o--o--o-- feature1
```
to 
```
-o--o--1-- master
```

where `1` is a well formatted commit message

Especially #1383  seeks to get from
```
-o--o-- master
  \
   o--o--o-- feature1
```
to
```
-o--o--1--2--3-- master
```
where `1`, `2`, and `3` are well behaved commit messages, regardless of if they have been on feature branch or not, but by providing fastforward mergeable feature branch with those well behaved commit messages just before shipping.

**Comment by kevgo** [comment]
`git ship` already allows editing the commit message, allowing you to arrive at the desired target state of `-o--o--1-- master`. What in addition do you need here? How exactly would commitizen plug into the `git ship` workflow? 

In your second example, I imagine that `git ship` uses the commit messages from the feature branch. If somebody doesn't like those commit messages, then they can change them on the feature branch using `git rebase -i` or give up and squash the commits into one when shipping. If commit messages are considered important, they should be a part of the code review, and not be changed after being approved. This means that `git ship` should make as little modifications as possible along the way.

Now that I think about it, when using the CodeHostingDriver, `git ship` shouldn't even ask the user to edit the commit message. It should just use the title of the pull request. I have created #1537 to track this idea.

**Comment by blaggacao** [comment]
>What in addition do you need here? 

Sometimes crafting those commit messgaes is rather complex, and might be projecr specific. A possibel schema:
```
<type>: <title>

[components: <components>]

[BREAKINV CHANGES: <breaking>]

[<reason>]

[fixes <issue>]
```

`cz commit` provides an interactive cli to ensure correctly filling in those values so they later can be parsed into a changelog. The key aspect is schema conformancen for automatic parseability.

>How exactly would commitizen plug into the git ship workflow?

In a scenario where `git ship` squashes the commit message, it would run as kind of a "prepare commit message hook" of a sort.

This idea is just a first stepping stone towards the ultimate goal that only parseable commits land on master, but it would support the workflow, where less proficient town member does a feature (best effort as to commit messages) and the approver crafts the final commit message on their behalf.

> If commit messages are considered important, they should be a part of the code review, and not be changed after being approved

Very good point!

> Now that I think about it, when using the CodeHostingDriver, git ship shouldn't even ask the user to edit the commit message. It should just use the title of the pull request

That might not always be enough, especially for the `<reason>` part in the above schema example, which should be as context free as possible. Often times, though, PR are highly contextual. Therefore reformulating is quite often necesary. In other scenarios, this is an interesting idea though. I'll comment there.

**Comment by kevgo** [comment]
Thanks, I understand your idea better now. I think if a team really wants their commit messages to be formatted in a certain way, then they have to enforce this on the Git level, for example with a [pre-merge-commit hook](https://git-scm.com/docs/githooks#_pre_merge_commit). Ideally, this hook runs on the Git server. One can also run it on the Git client as a convenience to catch mistakes earlier. It is important to enforce this on the Git level and not the Git Town level because people could be using other tools besides Git Town to commit. Only an enforcement on the Git level applies to all tools.

Since `git-town ship` just calls `git merge` under the hood, it would trigger this check and fail if the message isn't correct. I don't think a generic tool like Git Town should have opinions on whether or how a team wants to format their commit messages in a certain way. 

The workflow would be:
- Make sure the commits on your feature branch are correct. Use `git rebase -i` if needed to improve them. Use pre-commit hooks to ensure they are correct.
- When reviewing a feature branch, add a CI check or build status that checks all commits in the branch via commitizen and shows problems. In particular, human reviewers should check that the `<reason>` fields make sense. They should also check the pull-request description since that one is used as the commit message for the merge commit.
- When shipping a feature branch, use pre-merge-commit hooks on the client and the server that run commitizen to ensure that only properly formatted commits make it onto the main branch. Reject improperly formatted commits. Git Town will display the respective error message to the user.

**Comment by blaggacao** [comment]
Thanks, that would work just fine!
So to resume, you argue that instead of _crafting_ `git-town ship` messages, we should opt for reviewing & _enforce_ proper schema on PR title & description as in #1537 .

That is an interesting overall conceptualization. I'll have to sleep over this. Thanks for the input!
