### ISSUE TITLE
new CMS for website

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#1599]
The old CMS is based on Harp, which is no longer maintained, causes security alerts, requires Python 2 (officially discontinued) and old versions of GCC to install. Would be nice to use [Hugo](https://gohugo.io) as a replacement since it is Go-based (saving us from having to deal with the endless onslaught of security warnings for Node tools), well-maintained, and fast. 

Requirements:
- simple
- "edit this page" link

### Docsy

- https://themes.gohugo.io/docsy
- don't use the built-in example, fork the [KubeFlow website](https://www.kubeflow.org) documentation and use that as a baseline

pro:

- can look relatively polished
- supports multiple versions

con:

- not specific for technical documentation, doesn't have a lot of shortcodes
- needs a lot of work before it looks decent

### Book

https://themes.gohugo.io/hugo-book

pro: 
- tabs to show alternative instructions for different operating systems
- buttons
- multiple columns
- collapsible details
- tips 
- Mermaid
- good syntax highlighting
- different languages

con:
- has dark mode but cannot [dynamically switch to it](https://github.com/alex-shpak/hugo-book/issues/151)

**Comment by kevgo** [comment]
Currently leaning towards the "book" theme since it is simpler (i.e. more long-term stable than a website with fancy design that will age quickly) and supports more features like tabs, tips, and columns that we might be using.

**Comment by kevgo** [comment]
Library for creating animations to visualize how Git Town works: https://motion.dev

**Comment by kevgo** [comment]
CLI tool for simple website: https://github.com/rust-lang/mdBook/tree/master/guide

**Comment by sheldonhull** [comment]
I'm very versed in Hugo as I've wrestled through this for a long time with lots of tweaks for my site. 

The docs I use at [here](sheldonhull.com/docs) is the closest things I've found to being happy with. 

My 10 cents, is despite it being fantastic, I feel a tech doc site benefits much more from Material MKDocs. I've used that successfully many times and it's tremendously flexible, easy to get going, and beautiful out of the box. Recommend considering this despite my love for Hugo, since it focuses on exactly what you need. 

I'd be more than happy to PR a sample config with perhaps docker based run if you want to get you going. Just let me know if interested. I advocate for this tool all over (even have a few dedicated blog posts/reference) so would love to contribute back in some way until I wrap my ahead around adding a new provider :-)

**Comment by kevgo** [comment]
Thanks for your recommendation @sheldonhull! Material for MkDocs looks really nice! I have decided to keep the new website extremely simple and use [mdBook](https://github.com/rust-lang/mdBook) for the time being to get the transition done at all. I have read a few books created by mdBook and found it surprisingly useful. Work on the new website is underway in the [website2 branch](https://github.com/git-town/git-town/tree/kg-mdbook/website2).
