### ISSUE TITLE
contributor onboarding with nix-shell

### ISSUE THREAD

**Issue by blaggacao** [git-town/git-town#1625]
Recently I was getting my hands dirty with nix, the package manager.
nix has a very intriguing use case: the development shell.

Basically, with a single command: `nix-shell` it leaves you in a fully version controlled shell environment with all binary packages for x,y,z project's development environment pinned & included.

I did a PR for syndesis: https://github.com/syndesisio/syndesis/pull/8792#issuecomment-665392165

@kevgo Would you be eventually interested in contributing this technique to git town?

Internally, I'm using it everywhere, now. It's really powerful.

If not really relevant, please close! :wink:

**Comment by kevgo** [comment]
Thanks for the suggestion. Nix is helpful if one has to get a number of dependencies and tools on a machine. The Git Town installation is as clean as it gets because one only needs to put a single self-contained binary on a machine. We don't need Nix there at all. For development, all one needs is the Go toolchain and optionally Node.js. These are simple and straightforward to install on any platform. I think adding Nix would make things more complex than they are today without making anything simpler.
