### ISSUE TITLE
Git Town ship fails because it cannot delete tracking branch

### ISSUE THREAD

**Issue by cirego** [git-town/git-town#1626]
I'm not sure if this is related to a new repo that I started working on or if this is something that changed in a recent version of `git-town`.  I'm running `Git Town v7.4.0-dev (2020/07/29)` (built from `ca6f439a`).

Here is the error message that I'm getting:

```
[main] git push origin :cirego/branch1     
error: unable to delete 'cirego/branch1': remote ref does not exist                                                    
error: failed to push some refs to 'git@github.com:Org/repo.git'                                                       
                                                                                                                       
Error: cannot delete tracking branch for "cirego/branch1": exit status 1
                                                                                                                       
To abort, run "git-town abort".                                                                                        
To continue after having resolved conflicts, run "git-town continue".
```

Simply running `git town continue` will allow the `ship` command to complete.

Our repo does have the following option enabled under Repo Settings > Merge Button: "Automatically delete head branches". It seems to me that, when running `git town ship`, a failure to delete the remove ref should not cause the command to fail.

**Comment by kevgo** [comment]
Hey @cirego great to hear from you. This happens because GitHub automatically deletes the shipped branch on GitHub, so when Git Town tries to delete it (via `git push origin :cirego/branch1`), GitHub refuses because that branch no longer exists.

I have fixed this in https://github.com/git-town/git-town/pull/1280. You have to disable the `ship-delete-remote-branch` configuration setting by running this in your repo folder:

```
git config git-town.ship-delete-remote-branch false
```

Then `git town ship` will no longer delete the remote branch. This feature should be available in the latest release (7.4.0). Please reopen this ticket if you keep running into issues. Thanks!

**Comment by cirego** [comment]
Hey @kevgo: awesome and thanks for replying so quickly! Glad to hear it's already resolved!

Minor nit: `git town config` does not show this value. Likewise, it does not show whether or not a GitHub token is configured.

**Comment by kevgo** [comment]
Good point! I have created https://github.com/git-town/git-town/issues/1627 to track this. Thanks for the bug report!
