### ISSUE TITLE
How to correctly use with submodules

### ISSUE THREAD

**Issue by sheldonhull** [git-town/git-town#1638]
I have a hugo repo for a blog and it has a submodule folder for the theme per their recommendation.

When I run `git town sync` my go to to push and pull any changes, the submodule seems to have problems causing large amount of conflicts. I'm not sure how to handle this, or if git town is supposed to work with submodules. 

If submodules are supposed to work I could work up a test case to reproduce.

Running the git config in the submodule folder it returns

```
Main branch:
  [none]

Perennial branches:
  [none]

Pull branch strategy:
  rebase

New Branch Push Flag:
  false
```

In the parent branch it shows
```

Main branch:
  master

Perennial branches:
  [none]

Branch Ancestry:
  

Pull branch strategy:
  rebase

New Branch Push Flag:
  false

```

Thanks again for this tool. I'm always plugging it as it made feature branch workflow almost zero cost for my own dev work.

**Comment by kevgo** [comment]
Hi @sheldonhull thanks for your ongoing support, also on Twitter! Git Town currently does not officially support submodules. This means I'm not aware that anybody has ever tried using Git Town for managing code inside Git submodules. ]

I assume Git Town should work normally for the super-repo (the top-level repo containing the submodules). Using it to manage the submodules probably causes some issues. Please keep in mind that submodules are their own Git repositories with their own Git configuration. You have to configure Git Town inside the submodule again to prevent the issue you post above. This makes sense since submodules might use a different branching model than the super-repo.

Another thing that I can think of that might cause problems when running Git Town from a submodule is that Git Town changes into the root directory of the Git repo before changing branches. This is necessary because when Git Town is called from a subdirectory and changes to another branch that doesn't contain this subdirectory, Git Town ends up in limbo and cannot run any more shell commands. Here is the code that determines what the root directory is: https://github.com/git-town/git-town/blob/b70bcf3fba27e0620bcb3b771b03d4bc72ec67e2/src/git/runner.go#L961-L972.

**Comment by sheldonhull** [comment]
Thank you. It must be something wrong on this repo version locally.
My other machine didn't have a problem, but the current one conflicts, so guessing I failed to init the submodule or something on this specific instance. 

thanks!
