### ISSUE TITLE
Check for `init.defaultBranch` during config stage

### ISSUE THREAD

**Issue by FrazerClews** [git-town/git-town#1640]
I think it would be useful for git town to check if `init.defaultBranch` is set locally, introduced in Git 2.28. Skipping the step to manually set the main branch.

**Comment by kevgo** [comment]
Thanks for the pointer @FrazerClews! I'm glad this is finally configurable since `production` makes more sense for the stable branch. Git Town's concept of "main branch" is different from Git's default branch. For example, when using [Git Flow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) one would use `master` (or `production`) as the "default" Git branch and `develop` as Git Town's main branch (the branch into which feature branches get merged). Whatever branch names people end up using, Git Town will show it in the branch selection dialog. So I think there is nothing for us to do here.
