### ISSUE TITLE
`sync` fails with a `would clobber existing tag` if a remote tag was updated

### ISSUE THREAD

**Issue by kkom** [git-town/git-town#1642]
Hey!

In my company we're using the `currently-in-production` tag for, well... you can guess it. :) 

It's causing me issues with `git town sync`. The first command is `git fetch --prune --tags` and it fails in this way:

```
[new-aggregate] git fetch --prune --tags
(...)
 ! [rejected]              currently-in-production                     -> currently-in-production  (would clobber existing tag)

Error: cannot fetch: exit status 1
```

What's your thinking on this? Would you be in favor of updating the first command in the series to force the fetch? Or maybe there is something wrong that you can see with how my company is updating `currently-in-production` on the remote?

If it's a case of making some changes in git-town, I'd be more than happy to submit a PR!

Best,
Konrad

**Comment by kevgo** [comment]
Hey Konrad! My take is that you should consider using a `production` branch instead of a Git tag to point to the commit that is currently in production. Some background: Branches and tags are both pointers to commits in Git. The difference between them is that Git assumes that tags never change while branches can change. For example, you would use a tag to point to the commit that was shipped as version v1.0.1 and a branch to point to the commit that is currently deployed in production. The "git flow" branching model seems more idiomatic for the use case you describe: https://nvie.com/posts/a-successful-git-branching-model. I have used it myself, works very well!

**Comment by kkom** [comment]
Thanks @kevgo for the super quick response!

Our workflow is very simple: trunk-based development. So we don't have a `production` branch that we hotfix patches into, it's really much more similar to https://guides.github.com/introduction/flow/

I suspect that the reason why we chose tags for `currently-in-production`, rather than branches, is to add friction to the `currently-in-production` designation moving around in local git copies of the developers. So that if someone checks out `currently-in-production` and commits something to it, the branch is not deceiving them as to what is in production. We could use [pre-commit hooks](https://github.com/pre-commit/pre-commit-hooks/blob/9136088a246768144165fcc3ecc3d31bb686920a/pre_commit_hooks/no_commit_to_branch.py) for this, but that would add even more moving parts.

I think that it's exactly the difference between tags and branches which you mentioned, that made us choose tags. The only unfortunate consequence is the need to force update the `currently-in-production` tag when on production deployments, which is an antipattern.

I can check with the rest of the team to see if we're actually using the `currently-in-production` tag, but if the answer is yes (and I suspect we're also not planning to change our development and deployment model – it's very simple and works), what would you recommend regarding the usage of `git-town`?

I'm very excited about it (heard great things about it from ex-colleagues), but this issue would be blocking us from adopting it.

Thank you again and it would be great if you could let me know what your thoughts are. Maybe there is yet another solution that I didn't think of!

**Comment by kevgo** [comment]
Nice, trunk-based development rocks! A few more thoughts, hopefully helpful. I would still use Git branches to point to the commits in production. Yes, trunk-based development shouldn't have long-lived branches. But the `production` branch never contains different commits than `master`. It always gets fast-forwarded and never encounters any merge conflicts. It should be okay to use in a trunk-based workflow. By (ab)using Git tags as mutable pointers your company effectively has this additional production "branch" anyways, since branches are just mutable tags.

Yes, tags provide a bit more friction to prevent accidental updates by inexperienced developers, but also several footguns. Tags don't prevent accidental commits into the wrong place. One can still check out the `currently-in-production` tag and then make a commit. These commits will be lost because there are no pointers to them. The right solution here is the pre-commit hook, which prevents the commit with a clear error message so that people learn. Only people who actually check out the production branch and don't understand that they shouldn't commit into it need the pre-commit hook. Yes, setting up the hooks (which should be in your repo) is an additional one-time setup step (see [husky](https://typicode.github.io/husky) to make this easy), but so is the requirement or the required tooling to force-fetch updates or delete the local tag before pulling. Force-fetching regularly carries some risk of accidentally overwriting something in the local client. 

None of this is specific to Git Town - you will run into the same challenges with vanilla Git or any other Git client. Having said all this, one way we could address this in Git Town is with a config option that disables pulling tags. Steps to implementing this:

1. create a new configuration option `git-town.fetch-tags` (defaulting to `true`) similar to [shouldNewBranchPush](https://github.com/git-town/git-town/blob/master/src/config/config.go#L440-L453)
2. provide this config value to [Runner.fetch](https://github.com/git-town/git-town/blob/master/src/git/runner.go#L490-L497) and omit the `--tags` portion from the call to `r.Run` if the value is `true`
3. add integration tests with this feature disabled for at least one Git Town command, similar to https://github.com/git-town/git-town/blob/master/features/hack/new_branch_push_flag.feature
4. add this to the documentation of [git sync](https://github.com/git-town/git-town/blob/master/documentation/commands/sync.md), similar to how the documentation of [git hack](https://github.com/git-town/git-town/blob/master/documentation/commands/hack.md) documents the new-branch-push-flag.

**Comment by kkom** [comment]
Thank you so much for your advice again @kevgo! I'll discuss this internally and let you know what our thoughts are too!

Yeah, I was thinking about using husky like you say or [pre-commit](https://github.com/pre-commit/pre-commit-hooks/blob/9136088a246768144165fcc3ecc3d31bb686920a/pre_commit_hooks/no_commit_to_branch.py) for it. It still requires the developers to initialize the git hooks environment (so a new moving part), but it would have other benefits as well. I already use the pre-commit hook for not committing accidentally to the master branch on my personal projects. ;)

**Comment by kkom** [comment]
I think we can close this issue, it's clear that we should not be mutating tags. Thank you for your explanation again @kevgo !
