### ISSUE TITLE
releases via CI

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#1660]
Thoughts on setting up github actions for helping with releases?

Think that would be helpful. Just ran through the release process for 7.5.0 and haven't done the windows MSI release as I don't have a personal windows machine.

**Comment by charlierudolph** [comment]
As part of releases, do we need to update the website install page? Appears that has hardcoded reference to 7.4.0

**Comment by kevgo** [comment]
I'm not at all against this. It just needs a lot of work to get the Windows part stable enough. Right now it requires installing a number of external tools (.NET framework, Wix, go-msi, hub) using a variety of installers (Windows installers, hub only via Chocolatey). All of this is cumbersome and error prone because Windows doesn't have a proper app store (yet), so one has to resolve, download, and install all dependencies manually. This also causes substantial bit rot (newer versions of tools needing other dependency versions), which makes automation brittle. 

Given how rarely we make releases, the break-even point where automation will save us time/headaches over doing this manually (which takes only a couple of minutes) might never be reached. Hence, the Windows release process is manual for now. I still need a Windows box to support Git Town on Windows, so this isn't really a problem for me.

I just added the MSI installer to the 7.5.0 release.

Right now, we need to do a global search-and-replace for the old version number and replace it with the new version number as part of the release. Even if we DRY this up, we still need to manually update the version number somewhere. Doing it in all places isn't that much overhead.

**Comment by kevgo** [comment]
Here is a GitHub workflow that could be adapted to Git Town's use case. In particular, it has found a way to install Wix via the CLI. 

https://github.com/jam1garner/cargo-mextk/blob/master/.github/workflows/release.yml

**Comment by kevgo** [comment]
Current status: trying to sign up as a partner and reserve the app name. Microsoft's partner center goes into an infinite redirect loop and kicks me out. Will try again tomorrow.

**Comment by kevgo** [comment]
Ideally we publish to the Microsoft Store via [goreleaser](https://goreleaser.com/customization/winget). An alternative could be the [Microsoft Store Developer CLI](https://github.com/microsoft/msstore-cli).

**Comment by kevgo** [comment]
winget source code: https://github.com/microsoft/winget-cli

**Comment by kevgo** [comment]
Alternative app to create .msi installers: https://wiki.gnome.org/msitools/HowTo/CreateMSI

**Comment by kevgo** [comment]
### action items

- [ ] update goreleaser
- [ ] configure goreleaser to not create a GitHub release at all
- [ ] replace `hub` with the official `gh`
- [ ] release via winget instead of creating an msi #1479
- [ ] try to run this all on Windows
- [ ] run this on CI

**Comment by kevgo** [comment]
Status: GitHub has Windows-based runners that provide PowerShell access. It already has Chocolatey and Wix installed. The remaining tooling is available via Chocolatey.

I have created a `ps1` file that works locally, but go-msi fails on CI with the error:

> Rel: can't make D:\a\git-town-qa\git-town-qa\git-town.exe relative to C:\Users\runneradmin\AppData\Local\Temp\go-msi900612303

Seems a known error in go-msi: https://github.com/mh-cbon/go-msi/issues/51.

A possible reason is that the repo is on the D: drive while the temp folder is on the C: drive.

**Comment by kevgo** [comment]
We could use the workflow that publishes GitHub's official CLI: https://github.com/cli/cli/blob/trunk/.github/workflows/deployment.yml
