### ISSUE TITLE
Module name should end with /v7 otherwise it wouldn't be picked up by Go's indexing servers

### ISSUE THREAD

**Issue by yurivict** [git-town/git-town#1675]

**Comment by kevgo** [comment]
Thanks for bringing this to our attention. Can you please give an example for what exactly should look how? Or add a link to further information? Thanks! 😃

**Comment by yurivict** [comment]
[This](https://github.com/git-town/git-town/blob/main/go.mod#L1) line should be:
```github.com/git-town/git-town/v7```.

**Comment by kevgo** [comment]
Thanks for this example. Can you please provide some background why this is needed, and why it should be v7 and not v6 or v1? I have tried googling go indexing servers and how to configure code bases for them but didn't find anything useful.

**Comment by yurivict** [comment]
It should be v{major-version-number}.

Example: [Authelia project](https://github.com/authelia/authelia/blob/master/go.mod)

Why this is needed: some packaging systems (like FreeBSD ports) download dependencies based on Go indexing server records. Otherwise packaging of Go projects is more laborious.

**Comment by charlierudolph** [comment]
Is there no documentation that explains how this is suppose to work? Looks at the authelia example I see a number go.mod has a reference to v4 but don't see any v4 folder anywhere

**Comment by yurivict** [comment]
I'm not a Go expert. But Authelia compiles fine the way how it is.

**Comment by charlierudolph** [comment]
Initial set of docs I found: https://pkg.go.dev/about#adding-a-package

And git-town appears to be on there (though 7.3.0) https://pkg.go.dev/github.com/git-town/git-town

**Comment by kevgo** [comment]
The version number ("v7") at the end of the import URL does not require a folder with that name in the source. This is Go's [Semantic Import Versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) at play here. Relevant quote from that page:

> If the module is version v2 or higher, the major version of the module must be included as a /vN at the end of the module paths used in go.mod files (e.g., module github.com/my/mod/v2, require github.com/my/mod/v2 v2.0.1) and in the package import path (e.g., import "github.com/my/mod/v2/mypkg").

Authelia follows the same semantic import versioning as #1677 does, for example https://github.com/authelia/authelia/blob/master/internal/commands/build-info.go#L9.

So, I think the request in this issue is legit. Git Town is at version 7.x, hence the module definition must end with `v7` as well if we want to remain idiomatic with Go modules.

**Comment by kevgo** [comment]
@yurivict FYI this is shipped now. Hope this helps bundle Git Town on your end!

**Comment by yurivict** [comment]
Thank you, @kevgo , I'll wait for the release.

**Comment by kevgo** [comment]
Git Town 7.7.0 is out now.

**Comment by yurivict** [comment]
I updated the FreeBSD port to 7.7.0. It is now simplified to use Go's indexing servers.

Thank you for your help!
