### ISSUE TITLE
Git town sync with no push

### ISSUE THREAD

**Issue by sheldonhull** [git-town/git-town#1680]
Is there a way to set the git town sync command default to only pull rebase, but not push anything?
Asking as was considering setting up a pre-commit post-checkout step to run the git town sync oriented commands but would prefer to ensure there is not unexpected push, only pull/rebase oriented action happening at that stage.

**Comment by kevgo** [comment]
Right now there is no config option to avoid the push when running `git-town sync`.

If I understand you correctly, your use case is running `git-town sync` without pushing in a pre-commit hook. Some things to consider here:

- This makes commits slow since they now include multiple network operations (syncing the main branch and the feature branch).
- When there are merge conflicts, one runs the risk of losing uncommitted changes: `git-town sync` would be removed them from the codebase (by stashing them away) and leave the code base in an inconsistent with unresolved merge conflicts. The resolution is to resolve the conflicts and run `git-town continue` or `git-town abort`. That's not what one expects after running `git commit`. One should only run `git-town continue` after running a `git-town` command. It's probably better to not change the semantics of built-in Git commands like `git commit` too much.

The easiest way to go about this could be to run `git-town sync` and then commit normally. Maybe create a Bash script for that? Another option is running `git pull` in your pre-commit hook.

An interesting idea might be an additional Git Town command that syncs and commits. We haven't built one because we feel that Git Town shouldn't dictate that people should commit code via the Git CLI. Most people use GUI tools for that.

**Comment by kevgo** [comment]
Merging this ticket into #2715
