### ISSUE TITLE
`hack` should set the remote tracking branch automatically

### ISSUE THREAD

**Issue by aeneasr** [git-town/git-town#1683]
When doing

```
git-town hack <branch>
git push
git pull -ff
```

git complains that the branch has no tracked remote:

```
There is no tracking information for the current branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> add-blog-post
```

Can we make it so that `git-town hack` sets the tracking branch automagically?

**Comment by kevgo** [comment]
I can't reproduce your example: `git push` should already fail and it shouldn't even get to `git pull -ff`. Are there reasons preventing you from running `git sync` instead of `git push` here? `git sync` will create the remote tracking branch for your new branch.

Another possible solution is enabling the [new-branch-push-flag](https://github.com/git-town/git-town/blob/main/documentation/commands/new-branch-push-flag.md) setting in the Git Town configuration. It makes `git hack` create the remote branch, at the cost of it becoming slower (which is why it is disabled by default).

**Comment by aeneasr** [comment]
> Another possible solution is enabling the new-branch-push-flag setting in the Git Town configuration. It makes git hack create the remote branch, at the cost of it becoming slower (which is why it is disabled by default).

Got it! This is probably what I was looking for :) Thank you :)

**Comment by kevgo** [comment]
Some historical context: Initially `git hack` had the behavior you describe. We got feedback from the community that this makes `git hack` slow enough that many people avoid using it. So we made creating the tracking branch in `git hack` opt-in and rely that the first run of `git sync` creates the tracking branch.
