### ISSUE TITLE
please keep dotfiles on git sync

### ISSUE THREAD

**Issue by sascha-andres** [git-town/git-town#1882]
When running git town sync it removes dotfiles and dot-folders that are ignored but required for development purposes.

Is it possible to provide a list of "keep unversioned files"?

**Comment by sascha-andres** [comment]
Started digging into the code with the intention to provide this functionality as a PR. When running git town sync I get a message like this:

    Are you sure you want to clean all changes & sync with 'origin/main'? [y/N]:

So I did a grep on the repository on the words `clean all` but was unable to find it inside the codebase. Also running the code from within idea (run config see below) does not prompt nor does it remove anything that is removed when using git-town in the shell.

Output within IDE:

![image](https://user-images.githubusercontent.com/3052075/176348103-806e7de1-0706-47a7-85c2-8ee6221cb398.png)

Output on CLI:

![image](https://user-images.githubusercontent.com/3052075/176348241-4065aecb-496a-4c6f-8603-d50da337be97.png)

Can you provide a hint where to start?

![image](https://user-images.githubusercontent.com/3052075/176347839-26419841-76c0-40a4-afbc-82b90f79200e.png)

**Comment by charlierudolph** [comment]
Hi @sascha-andres.

It seems like your CLI is executing something other than `git-town sync`

**Comment by kevgo** [comment]
Hi @sascha-andres Git Town leaves files listed in `.gitignore` alone, see our [end-to-end test that proves it](https://github.com/git-town/git-town/blob/main/features/sync/features/ignored_files.feature).

As @charlierudolph suggested, you seem to call another Git tool instead of Git Town. Try running `which git-sync` in a terminal, it should point you to the command that is actually running here.

If you want to continue investigating Git Town, please open a terminal and run `git-town sync` in your directory. If that still produces the problem, please post the output again and tell us which Git version you use, i.e. the output of `git --version`.

**Comment by kevgo** [comment]
Closing this as non applicable, please reopen with additional information if you still think this is a Git Town problem.

**Comment by sascha-andres** [comment]
@kevgo You were right. I install git through a script with [git-extras](https://github.com/tj/git-extras) on top-. They do have a git-sync (which was the culprit). There are also open tickets for git-extra asking to change the behavior (https://github.com/tj/git-extras/issues/660)
