### ISSUE TITLE
Support `trash` command if available instead of regular removing

### ISSUE THREAD

**Issue by kopach** [git-town/git-town#1895]
`git sync` takes ages for me due to a lot of files under `node_modules`. To quickly remove `node_modules` I usually use `trash` command  (https://formulae.brew.sh/formula/trash) instead of `rm -rf` myself.
There should be alternatives for every OS.

**Comment by kevgo** [comment]
Can you please summarize which feature or documentation update you are proposing?

**Comment by kopach** [comment]
1. if `trash` command available (`which trash`)
	1. get list of files to be removed during `git clean -dfx` (o whatever command is actually used)
	2. remove those files using `trash` command first (e.g. `trash node_modules`
	3. additionally `git clean -dfx` could be executed
5. otherwise just use `git clean -dfx`

benefit - `trash` is way faster as it doesn't actually remove file, but just moves it to trash

**Comment by kevgo** [comment]
Git Town doesn't run `git clean` because Git Town doesn't have any business removing any files from the user's hard drive. Quite the opposite, we try pretty hard to make sure that no files (tracked or untracked) get lost when running Git Town commands.

AFAIK Git and thereby also Git Town don't touch files that Git it doesn't track. So if you have a `node_modules` folder that isn't tracked by Git, that shouldn't make your `git sync` slower.

If you really want to delete some of your untracked files from your hard drive, I suggest you create a custom shell script that first runs `trash` and then `git sync`.
