### ISSUE TITLE
Prevent merging main into release when running git town sync from sub-release branch

### ISSUE THREAD

**Issue by gontovnik** [git-town/git-town#2040]
Hey!

Is there a way to prevent `git town sync` from merging `main` into `release` when running `git town sync` from a branch that is created from `release`?

We usually cut the `release` branch out of `main` and then kick off bug fixes on the `release` branch by creating `release-fix/NAME` branches. And I got used to calling `git town new-pull-request`. But the current problem is that it merges `main` to `release`, then `release` to my bug fix branch.

**Comment by kevgo** [comment]
You have a good use case for [perennial branches](https://www.git-town.com/commands/config-perennial-branches.html). Perennial branches are long-lived branches that stand on their own, i.e. don't receive updated from the main development branch. To set this up:

1. when it's time to make another release, cut the `release` branch from the `main` branch:
  
   ```
   git hack release
   ```

1. mark the `release` branch as a perennial branch so that it no longer receives updates from `main` when syncing it:

   ```
   git town config perennial-branches update
   ```

1. kick off a bug fix on the `release` branch:

   ```
   git checkout release
   git append release-fix/1
   ```
   
   The [append](https://www.git-town.com/commands/append.html) command creates the new branch as a child of the current branch. The [hack](https://www.git-town.com/commands/hack.html) command creates the new branch as a child of the main branch, no matter what branch you are on.

1. sync the bugfix branch:

   ```
   git sync
   [release-fix/1] git merge --no-edit release
   Already up to date.
   ```

   It doesn't sync `main` anymore!

1. create a pull request for the bug fix:

   ```
   git new-pull-request
   ```

   This creates a pull request from `release-fix/1` into `release`.

**Comment by kevgo** [comment]
Git Town doesn't allow shipping perennial branches. When you are done with the release and want to merge the bug fixes made on the `release` branch into `main`, you need to either do that manually, or convert the `release` branch back into a feature branch so that `git new-pull-request` works on it.

```
git town config perennial-branches update
```

Remove the checkbox from "release" in the dialog and hit ENTER.

I have just filed https://github.com/git-town/git-town/issues/2042 for a programmatic way to set/remove perennial branches.

**Comment by gontovnik** [comment]
Thanks! That is super helpful :)
