### ISSUE TITLE
Handling of already-checkout branches

### ISSUE THREAD

**Issue by koppor** [git-town/git-town#2197]
I use git-worktree to have several branches checked out in parallel. This might confuse tooling.

In the concrete case, if the upstream branch is checked out in another dirctory when using `git-town sync`, the sync fails:

![image](https://user-images.githubusercontent.com/1366654/229991242-8bb6c1dd-75fe-429d-90c4-23afe2723057.png)

Could `git-town` just stop processing if a "fatal" error occurs?

OK, even better it would be:

1. Go to the other directory
2. Store revision
3. Check out `HEAD^`
4. Go back to the directory
5. Continue until finihs
6. Go to the other directory
7. Checkout out the revision stored in step 2

**Comment by kevgo** [comment]
One way to prevent this issue would be to clone your two repositories (the original at https://github.com/JabRef/jabref and the fork at https://github.com/koppor/jabref) separately. Then develop within the latter, as described in https://github.com/git-town/git-town/issues/1181#issuecomment-1498006766.

Let's continue the conversation around the missing Git worktree support at https://github.com/git-town/git-town/issues/2134. I'm going to close this ticket as a duplicate. If this is not a duplicate, please comment here and I'm happy to reopen this issue here. Thanks! :slightly_smiling_face:
