### ISSUE TITLE
Support amend workflow

### ISSUE THREAD

**Issue by wederbrand** [git-town/git-town#2223]
I came to git-town for it's nested feature branches, a pattern I'm always using when coding features.

However, as I work on them I normally also amend to existing commits to make it very easy to review.
I might have a commit "cleanup and refactoring" that doesn't logically change the code and then a couple of more commits that gradually implements a new feature.

However, everytime I run "git town sync" it re-fetches my pre-amended commits leaving me with a very messy tree of commits.

I'd like for an option that works better for single-developer-workflows. 
* jump back to master, pull/rebase as git-town does today
* same for all parents but don't rebase from the origin branch, instead force push it after rebasing is completed
* for all nested feature branches

**Comment by kevgo** [comment]
@wederbrand Glad to hear you enjoy the nested feature branch functionality. Please make sure you set the [sync-strategy](https://www.git-town.com/preferences/sync-strategy.html) config option to `rebase`:

```
git town config sync-strategy rebase
```

When set to `rebase`, Git Town should be doing what you have in mind: It will rebase your feature branches against their parent branches and push them via `git push --force-with-lease`. Here is the [end-to-end spec](https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/rebase_sync_strategy/sync_current_feature_branch_using_rebase.feature) that lists the exact commands Git Town would run.

**Comment by wederbrand** [comment]
I will make an attempt to recreate it but from just reading that spec I think that line 22 shows the "error". I'm not interested in rebasing the feature branch from origin since I've done "git commit --amend" on commits that has already been pushed. 

Doing that rebase will leave me with two commits, one matching origin and one containing what I amended locally.

While we're at it, I also find line 20 confusing since my workflow never allows me to push to origin/master without a PR (through bitbucket).

Here is a use-case:

```
git town hack testing
echo "testing stuf" > test.txt
git commit -am'testing some stuff'
git town sync 
(the branch is created on origin)
(someone complains about spelling stuff wrong in the PR, so I fix it)
echo "testing stuff" > test.txt
git commit -a --amend -CHEAD
git town sync
(instead of having the fixed version pushed to origin I now have merge conflict.)
```
result of this is

```
commit 3ed6641d5eb442efef74bae226566950d1f7e44
Author: Andreas Wederbrand <andreas.wederbrand
Date:   Fri Apr 21 22:59:39 2023 +0200

    testing some stuff

commit 5b4cd2c315d593e1a78579c4a7f0d20b4306de1
Author: Andreas Wederbrand <andreas.wederbrand
Date:   Fri Apr 21 22:59:39 2023 +0200

    testing some stuff


```
where the second commit contains the fixes and the first still contains the now fixed error.

Cheers.

**Comment by kevgo** [comment]
I agree that it would be nice if `git sync` would overwrite outdated commits on the remote branch when amending these commits locally. Unfortunately, I don't see a way to implement this because of limitations that exist in Git today.

When you amend a commit, Git doesn't "update" this commit because Git commits are immutable. Instead, Git creates a completely new commit. It would be great if Git remembers that this new commit is an updated version of an existing commit so that tooling can replace the latter with the former. But afaik Git doesn't remember this relationship between these two commits. So, after amending a commit locally, your local branch has one commit and its remote branch has completely different, seemingly unrelated, commit.

Git Town must never lose data, so it plays it safe and keeps both commits. You (Andreas) know that it's safe to throw away the commit on the remote branch, but Git and therefore Git Town doesn't. 

The easiest solution is that you get rid of the outdated commit yourself while amending by force-pushing the local branch manually after amending. Meaning you run this command when amending:

```
git commit -a --amend -CHEAD && git push --force
```

To make this easier, you could create a little Bash/CMD script that contains these two lines. I have one called `gap` ("git amend and push"). 

Once you have force-pushed the amended commit to the remote, the normal `git sync` works again and won't mess up with your commits again.

**Comment by kevgo** [comment]
> my workflow never allows me to push to origin/master without a PR

That's an excellent point. I have created https://github.com/git-town/git-town/issues/2224 to track this idea.

**Comment by kevgo** [comment]
Here is another work-around if you want to keep fast local commits and don't want to wait for the push to remote on every commit:

- keep committing locally using `git commit --amend`
- when you are ready to sync, run `git push --force-with-lease && git-town sync`

**Comment by bryanlarsen** [comment]
Note that despite intentions git town does lose data in this scenario.

Example: if you have two commits in a branch A and B, sync the branch, then use `git rebase -i HEAD~2` to squash the two commits together creating commit A+B and then sync the branch git town throws away the A+B commit since after bringing back A and B, A+B is now an empty commit and git discards it without `--allow-empty`.   In my case, it's during the squash that I compose a nice commit message, so git town threw that nice message away.     I was able to resurrect it from the reflog, but if git-town is targetting beginners, the reflog is voodoo magic.

**Comment by kevgo** [comment]
Please note that you can always run `git town undo` to undo the last Git Town command and go back to exactly where you were before you ran that command. The citizens of Git Town never need to resort to reflog voodoo 😉 

I assume you rebased commits that were already pushed to the tracking branch. If so, you need to force-push your new `A+B` commit to the tracking branch as well and then everything works. As discussed in this ticket, you are changing already agreed-on, committed-to, and published history. If you change this history, you need to make sure that you notify every other party that has expects the previous state to never change about your (at this point unexpected) change. In this case the other parties are the tracking branch and possible child branches.

I wish I knew a way to make this work. But AFAIK that's just how Git works. There are many safe Git commands that Git can be automatically propagate and replicate: commits and merges. Git also gives you access to its inner workings and lets you do unsafe voodoo things like rebases. Like with `sudo`, you need to know what you do, think before you type, and it's up to you to do such open-heart surgery correctly or bad things will happen.

I think running a simple `git pull --rebase` would also delete your commit in your situation.

**Comment by kevgo** [comment]
@wederbrand @bryanlarsen I keep thinking about your use case, which is pretty common. What I don't like about my suggestion is that people have to create custom bash scripts to work around this. Git Town started as a collection of such bash scripts, and got formalized into a tool to free developers from having to create such bash scripts.

I have outlined a possible Git Town command that would support the amend workflow better: #3177. If you are still interested in Git Town support for this, I would appreciate if you review #3177 and comment there if something like this would be useful to you. Thanks!

**Comment by kevgo** [comment]
Another idea in this context is https://github.com/git-town/git-town/issues/3182. It would allow people to use the normal `git rebase` and then `git sync` everything properly as long as they are the only ones working on the respective branch.

**Comment by kevgo** [comment]
A pretty elegant solution for this was shipped in v13. Please try it out and reach out with any feedback!

**Comment by vineus** [comment]
> A pretty elegant solution for this was shipped in v13. Please try it out and reach out with any feedback!

Hello there!

This works well, except when you amend a commit "mid stack": as the commit changes, git will consider it's a conflict when syncing the child branch.

```
A
  \
   B
     \
      C
```

If you:
```bash
git town switch B
git commit --amend 
git town sync
git town switch C
git town sync
```

then you'll have a conflict on rebasing `B` because the remote is in the "new" state and the local (of C) is still in the "old" state.

Solving the conflict is easy: just accept everything from "theirs" (we want to be exactly in the remote state)

graphite.dev "solved" the issue by rebasing all the "down" branches after an `amend` (they offer a special `modify` command that does the amend and "re stack" all child branches)

*thank you so much for your work by the way! Coming from graphite.dev that I can't use in my new company, your tool is a great alternative!*
