### ISSUE TITLE
Version Doesn't report the version

### ISSUE THREAD

**Issue by delmendo** [git-town/git-town#2246]
I'm using git-town 8.0 on ubuntu --git-town_8.0.0_linux_intel_64.deb

`git town version`

This doesn't report a version - I get

`Git Town  ()`

**Comment by kevgo** [comment]
Most likely this happens because when switching to [goreleaser compiling the release binaries](https://github.com/git-town/git-town/blob/21c5dec582f0fc266161d83a2bb3fe6d311a1d14/Makefile#L58) it no longer sets the needed `ldflags`.

**Comment by kevgo** [comment]
https://goreleaser.com/customization/builds/#passing-environment-variables-to-ldflags

**Comment by kevgo** [comment]
FYI the fix for this has been released as [v10.0.0](https://github.com/git-town/git-town/releases/tag/v10.0.0). Apologies for the delay, this PR came in the middle of a large-scale product cleanup that involved a number of breaking changes that need to be shipped together but took a while to finalize and test.
