### ISSUE TITLE
Release not properly tagged

### ISSUE THREAD

**Issue by alerque** [git-town/git-town#2256]
The [v9.0.0](https://github.com/git-town/git-town/releases/tag/untagged-c5121e4d876a7f56b01f) release is tagged `untagged-<some_hash>` (that isn't the SHA of the commit being tagged). That doesn't inspire confidence in a Git tooling repository ;-)

Please `git tag v9.0.0 7e7afda` and push the tag to the repo.

**Comment by alerque** [comment]
v9.0.0 tag is now uploaded (pointing to a commit one older than the previous GH Release was marked at), b1d9998f3a5c8f5345b2529e3429135ecac45d41.

**Comment by kevgo** [comment]
@alerque thanks for catching and raising this issue. I'm reworking the deployment scripts to avoid similar problems in the future. 

The release now uses tag `v9.0.0` which I forgot to push when making the release. The process is admittedly too manual right now because releases happening infrequent enough that there isn't much available bandwidth for release automation.

I wish GitHub would not make up an `untagged-<some_hash>` tag when a Git tag for a release is missing, and it would not simply pick the latest commit on the main branch for it. In our case the main branch already contained a new commit made after the official release was cut.

On the good side, the quality of the tool itself is enforced by a comprehensive suite of end-to-end tests. Every commit on `main` is fully working and shippable. Releases mostly just bundle up changes so that Git Town users have to read release notes only once in a while :slightly_smiling_face:
