### ISSUE TITLE
Git town completions for zsh not working on OSX.

### ISSUE THREAD

**Issue by gstamp** [git-town/git-town#2267]
If I follow the docs I get an error in OSX:

```
❯ git-town completions zsh | source
source: not enough arguments
```

If I write the output of the completions to a file and source that file I no longer have the error but the completions fail to work.

**Comment by guusw** [comment]
Seems to be the same on windows (had to `source <(git-town completions zsh)` but no completions anyways)

**Comment by kevgo** [comment]
I’ve updated the instructions to load auto-completions for zsh:

```zsh
source <(git-town completions zsh)
```

If you encounter the `command not found: compdef` error, you can resolve it by running:

```zsh
autoload -Uz compinit
```

This solution works on my setup (zsh 5.9, macOS 14.6.1) so I'm going to close this ticket for now.

Let me know if there’s anything else you need!

**Comment by jeffwright13** [comment]
Two items:
- The updated command no longer produces the `source: not enough arguments` error, but still does not work. 
- Invoking help (`git town completions -h`) still shows the old (erroring) command:
```
git town completions -h
Generate auto-completion for bash, zsh, fish, or PowerShell.

When set up, "git town <TAB>" will auto-complete Git Town subcommands.

To load autocompletion for Bash, run this command:

	git town completions bash | source

To load completions for each session, add the above line to your ~/.bashrc file.


To load autocompletion for Zsh, run this command:

	git town completions zsh | source

To load completions for each session, add the above line to your ~/.zshrc file.


To load autocompletion for Fish, run this command:

	git town completions fish | source

To load completions for each session, add the above line to your ~/.config/fish/config.fish file.


To load autocompletions for Powershell, run this command:

	git town completions powershell | Out-String | Invoke-Expression

To load completions for each session, add the above line to your PowerShell profile.

Usage:
  git-town completions [bash|zsh|fish|powershell]

Flags:
  -h, --help              help for completions
      --no-descriptions   disable completions description for shells that support it
```

**Comment by kevgo** [comment]
Hey @jeffwright13, thanks for bringing this up!

Based on your feedback, I've updated the help text for the CLI tool in #4153, and I've also added a link to the autocomplete setup in the [configuration guide](https://www.git-town.com/configuration) via #4154.

With these updates, this information should now be more discoverable. My goal is for end users to primarily rely on the [website](https://www.git-town.com) for guidance rather than having to sift through GitHub issues. I’d like to keep the issues focused on bug reports and feature ideas.

That said, I’m definitely open to suggestions on improving the user overall experience. Any feedback—big or small—would be greatly appreciated!

**Comment by jeffwright13** [comment]
Hi Kevin,

I'll try to verify the fix soon. I did a quick stab at it but wasn't able
to immediately see that the new version made any difference.

But more important than that - I have occasion to put git-town through its
paces for stacked PRs right now. I have 3 bugs that were discovered in the
past few days that depend upon one another. Bug 2410 has already been fixed
and the changes pushed to master using our usual git PR process. Bug 2415
was found as a result of more thorough testing of the fix for 2410. And bug
2416 was found last night, and is a direct result of discovering 2415. I
have fixes for both 2415 and 2416, but they are not committed yet.

What I'd like to do is use this as an excuse to test-drive the git-tow
stacked PRs workflow. Any suggestions?

Thanks, Jeff

**Comment by kevgo** [comment]
@jeffwright13 please note that I only fixed documentation. The updated documentation is here: https://www.git-town.com/commands/completions. Afaik the implementation works.

You can find an overview for how to use Git Town to implement stacked PRs here: https://www.git-town.com/stacked-changes.

Please reach out if anything there is unclear, or if you have any other suggestions. Thanks! 🙏
