### ISSUE TITLE
Add command to visualize stack / nested branches

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#2639]
When using nested branches, it's often nice to be able to tell where you are in the chain.

I'd like a command that can display something like this:

- main
  - feature 1
    - **feature 2** (you are here)
       - feature 3
         - feature 4
  
Ideally, this would also be added to the pull request's body at the top/bottom. So that it's clear for the reviewer how things are stacked.

Optionally, the main branch should be visible or not.

**Comment by zeronacer** [comment]
You could use `git town switch` for this. It displays the branches in hierarchical order and allows you to navigate your repo with an interactive prompt.

**Comment by ruudk** [comment]
Thanks for the tip. That's indeed nice!

**Comment by kevgo** [comment]
Thanks for reaching out! The (excellent) idea to add a visualization of the stacked changes to the respective PRs is being tracked at https://github.com/git-town/git-town/issues/3003. Please upvote this ticket if you want to see support for that idea.

Since all ideas in this ticket are addressed, I'm going to close it now. As always, please reach out if you have additional thoughts, ideas, or feedback. Thanks!
