### ISSUE TITLE
Add option to turn off rebasing remote origin branch

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#2648]
I have the same problem as described in:
- https://github.com/git-town/git-town/issues/2223

I understand that Git Town never wants to loose data. But in my workflow, I only work on 1 machine, and never have commits on the origin branch that I pushed there from some other place. I always do everything from the same git repository on my machine.

It would be great if I could turn off the option to pull my feature branch from the origin.

So in the case that I amended a commit, running git sync would just overwrite the remote branch.

**Comment by kevgo** [comment]
Writing down a (dopey) idea for how to possible support this (widespread) use case. This would only work if you amend commits and never change the commit messages:

1. You enable a hypothetical Git Town config setting called `amend-workflow-and-always-one-developer-per-branch`.
2. You run `git sync`. Git Town stores the SHA of all commits in the current branch in Git Town's runstate file at `~/.config/git-town/runstate/<repo_path>.json` (which already stores the state of the currently running Git Town command).
3. You code and amend local commits.
4. You run `git sync` again. Git Town compares the current commits against the stored commits. If all commit messages match, and the timestamps of the local commits are later than the stored timestamps, and the `amend-workflow-and-always-one-developer-per-branch` setting is active, and all commits on the local and the tracking branch are indeed from you, and only the SHAs are different, then Git Town would force-push the local commits to the remote branch.

Such a feature still feels like a pretty large footgun to me. There are a lot of pretty common situations where this would leads to data loss. It also seems fickle since this would stop working when changing any of the commit messages or adding/removing commits. So I'm not sure this is a production-grade concept. Also, such a feature won't be implemented for a while since there are much lower-hanging fruits and there are plenty of very usable and safer workarounds.

**Comment by ruudk** [comment]
Requiring the commit message to be the same is a no for me. I like to make improvements to existing commit messages too.

It's sad that git doesn't have a way to attach additional metadata to a commit. That would say when editing the commit. Or when squashing 2 commits together.

**Comment by kevgo** [comment]
I agree it would be much better if Git Town would support the full range of changing commits, including changing content, commit messages, or reorganizing commits via interactive rebase. Another idea how to support all of this: 

At each invocation of `git sync`:

- store a fingerprint of the commits in each feature branch (name, SHA, timestamp etc) in Git Town's runstate file
- detect whether changes happened to the remote branch by comparing the SHA of the remote branch before and after running `git fetch`
- detect amend/rebase activity on the local feature branch by comparing the commits in the local branch with the stored commit fingerprints in the runstate file

Now there are four possible situations with clear courses of action:
  
- existing local commits changed && no changes to remote branch --> force-push the local branch
- existing local commits changed && changes to the remote branch --> exit with an error message saying "you changed your local commits but there are now also new commits at the remote branch, so I don't know what to do here and you figure it out" and let the user resolve the situation manually
- existing local commits not changed but new commits added --> push the local branch
- no local changes && no remote changes --> do nothing

This feature would have the benefit that it eliminates the (very real) risk of a user running `git push --force` manually and accidentally overwrites changes at the remote branch that the user wasn't aware of.

There are a few edge cases that I have to think through more, like what happens if the user runs `git fetch`, `git pull`, `git pull --rebase`, or `git push` manually in between syncs.

**Comment by kevgo** [comment]
An alternative would be storing the SHA of the remote branch in the runstate file as well.

When the user runs `git fetch` and there were changes to the remote branch: `git sync` will still detect changes to the remote branch, no problem.

When the user runs `git pull --rebase` and there were changes at the remote branch but no local changes: `git sync` falsely detects non-existing changes to the remote branch and non-existing changes to local commits and exits with an error message instead of syncing. Not a good situation.

When the user runs `git push`: `git sync` will falsely detect non-existing changes to the remote branch and refuse to sync. Not a good situation.

**Comment by kevgo** [comment]
@ruudk Git Town 13.0 introduces support for your scenario. I'm going to close this ticket as completed. If there are additional ideas of feedback, please don't hesitate to comment on this ticket or open a new one. Thanks!
