### ISSUE TITLE
Invalid git repo with custom port

### ISSUE THREAD

**Issue by zifeo** [git-town/git-town#2654]
```bash
git config git-town.code-hosting-origin-hostname gitlab.example.com
git config git-town.code-hosting-driver gitlab
git remote get-url origin // outputs: ssh://git@git.example.com:4022/a/b.git
git repo // redirects to https://gitlab.example.com/4022/a/b
```

**Comment by kevgo** [comment]
I just added end-to-end tests that verify that the behavior you need works:

- for git repo: https://github.com/git-town/git-town/blob/b4811743d1c7d899a59a97b5afaf461ce8079f0d/features/repo/features/self_hosted.feature#L21-L29
- for git new-pull-request: https://github.com/git-town/git-town/blob/b4811743d1c7d899a59a97b5afaf461ce8079f0d/features/new_pull_request/features/self_hosted.feature#L22-L30

Could there be a configuration issue on your end? One thing that stands out to me is that you configured `git-town.code-hosting-origin-hostname` to use the domain `gitlab.example.com` while your Git repo's origin uses the domain `git.example.com`.

**Comment by kevgo** [comment]
Great point, that makes sense.

**Comment by kevgo** [comment]
@zifeo thanks for the guidance on expected behavior. #2730 makes Git Town use the standard port for URLs opened in the browser no matter which port the origin URL uses. It will get released as part of Git Town v11 in a couple of days.

Please note that the `git-town.code-hosting-origin-hostname` setting in your example is only for SSH identities, see https://www.git-town.com/preferences/code-hosting-origin-hostname.

I cannot reproduce the problem where you get `https://gitlab.example.com/4022/a/b`. I'm also on a Mac. Hopefully the point is moot since the port is now omitted. If this problem persists, please open a separate ticket for it. Thanks! 🙏

**Comment by zifeo** [comment]
@kevgo lovely, thanks!
