### ISSUE TITLE
kill all branches without upstream

### ISSUE THREAD

**Issue by JCB-K** [git-town/git-town#2707]
It happens fairly often that I (or somebody else) merges a PR online, rather than through the CI. Is it possible to kill all local branches without an upstream?

I'm happy to implement this myself, but I'd need some guidance.

**Comment by kevgo** [comment]
What exactly do you mean with "upstream"? 

Since Git Town 10 `git sync` deletes the local branch if its tracking branch (the branch called `origin/<branchname>`) was deleted at the remote. If you want to delete the local counterparts of all shipped branches, run `git sync --all`. This removes all shipped branches from your computer and updates the rest.

**Comment by JCB-K** [comment]
I mean the matching branch on the origin, not sure if I used the correct terminology.

```
Switched to branch 'example'
Your branch is based on 'origin/example', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
  ```
  
  Didn't know about the `-all` flag, thanks! Will close this.
