### ISSUE TITLE
Incorrect Self hosted BitBucket  PR URL

### ISSUE THREAD

**Issue by smaldored** [git-town/git-town#2914]
Hey there,

I am pretty new to using git-town, but I believe I have it set up correctly. `git hack`, `git sync` works. `git propose` works up until the URL it creates for the PR.

We have a self hosted Bitbucket server where our repos stay.

Here is the URL `git propose` creates:
`open https://stash.company.local/project/repo/pull-requests/new?source=git-town-test&dest=project%2Frepo%3Adev`

But, this is an invalid URL. 

It needs to look like this:
`open http://stash.company.local/projects/project/repos/repo/pull-requests?create&targetBranch=dev&sourceBranch=git-town-test`
Notice `http` instead of `https`, `/projects`, `/repos`, `?create` instead of `/new?`, `sourceBranch` instead of `source`, `targetBranch` instead of `dest`

Here is what I get when running `git config --get-regexp git-town` :
```
git-town.code-hosting-platform bitbucket
```

Do I need to use `git-town.code-hosting-origin-hostname=<hostname>` for something? Is there some sort of configuration I am missing?

I've come across #1164 which seems like it is a similar issue to what I am seeing. 

Thanks for the help in advance

**Comment by kevgo** [comment]
Thanks for reaching out. Your configuration looks okay to me. The issue seems that different BitBucket versions use different URLs for creating pull requests. Support for distinguishing different BitBucket versions would have to be added to Git Town.

To create pull requests on BitBucket, Git Town uses the URL reported by one of our users: https://github.com/git-town/git-town/issues/2019. If this URL doesn't work for you, I suspect you work with a different version of BitBucket and your version uses a different URL for creating pull requests. Which BitBucket version do you work with?

`git-town.code-hosting-origin-hostname=<hostname>` is for when you use different SSH identities. See https://www.git-town.com/preferences/code-hosting-origin-hostname for details. In your case, Git Town already correctly uses `stash.company.local` as the hostname, so your configuration seems okay.

To make this work for you, it seems like we would need to add a `bitbucket_version` configuration setting that makes Git Town use the right URL for the bitbucket version. This feature doesn't exist yet.

**Comment by smaldored** [comment]
Thanks for getting back to me.

It looks like we are using `Atlassian Bitbucket v7.4.1` and Bitbucket Server. From the looks of #2019 that is for the Bitbucket Cloud.

See https://developer.atlassian.com/server/bitbucket/rest/v815/api-group-pull-requests/#api-api-latest-projects-projectkey-repos-repositoryslug-pull-requests-post for creating a PR with bitbucket server API.

**Comment by kevgo** [comment]
Interesting that BitBucket Cloud has such a different URL structure compared to the self-hosted product. Since [Atlassian is moving to cloud-only](https://www.atlassian.com/migration/assess/journey-to-cloud), I'm a bit hesitant to invest bandwidth into adding support for the deprecated self-hosting product. But I would accept a pull request that adds it. Is your organization considering moving to the cloud offering?

Thanks for the link to the API. Git Town intentionally doesn't create pull requests via the API. Doing so would mean Git Town needs to provide a UI for the user to enter all the PR data (title and description, tag reviewers, link tickets, etc) on the command line. For each of the supported hosting services (BitBucket, Github, GitLab, Gitea). It's more ergonomic to let our users use the web-based page that they are used to. The web page is maintained by the hosting provider and offers all the PR features that the hosting provider supports.

**Comment by Crocmagnon** [comment]
Hello!
I'm trying to use git-town at my company where we also have a self-hosted bitbucket instance. We have the datacenter version, which Atlassian still sells and supports. They released an LTS not too long ago.
https://www.atlassian.com/enterprise/data-center/bitbucket

git-town looks very promising especially for the stacked branches workflow, I'd love for it to support our code forge ☺️

Let me know if I can be of any help in providing more info or even contributing code.

**Comment by kevgo** [comment]
@Crocmagnon Thanks for reaching out and offering to help! With my current backlog, the quickest path to adding the bitbucket-datacenter driver is if you take the lead on building it. It should be straightforward, and I’m more than happy to guide you through the process. Here’s an outline to get you started:

All the hosting service code lives in the [hosting package](https://github.com/git-town/git-town/tree/main/internal/hosting). Within it, there’s already a sub-package for the [Bitbucket Cloud driver](https://github.com/git-town/git-town/tree/main/internal/hosting/bitbucketcloud). Since Bitbucket Cloud and Datacenter have key differences, the best approach would likely be to create a new driver specifically for Datacenter.

To do this, copy the `bitbucketcloud` folder and rename it to something like `bitbucketdatacenter`. Then adjust the code in the copied files as needed for Datacenter’s specifics. The structure and functionality should be pretty self-explanatory, but if anything isn’t clear, don’t hesitate to ask questions.

Next, you’ll need to configure the new driver in Git Town’s configuration file. You can do this by adding a new constant, `HostingPlatformBitbucketDatacenter`, to the [HostingPlatform enum](https://github.com/git-town/git-town/blob/main/internal/config/configdomain/hosting_platform.go).

The [developer docs](https://github.com/git-town/git-town/blob/main/docs/DEVELOPMENT.md) might be useful. If you run into any roadblocks, feel free to open a draft PR, even with failing tests or incomplete code, and I’ll help you troubleshoot and get this feature shipped. Looking forward to collaborating on this!

**Comment by Crocmagnon** [comment]
Awesome! Thank you for your detailed message 🔥 
I can't commit on any ETA but I'm interested in making it work for my team. I'll ask here if I need.

**Comment by kevgo** [comment]
I think the issue in is ticket was addressed in [v16.7.0](https://github.com/git-town/git-town/releases/tag/v16.7.0). Closing it for now. Please comment or reopen if this is still a problem.
