### ISSUE TITLE
Process request: Consider using Commitzen in commits to prefix changes with Conventional Commits

### ISSUE THREAD

**Issue by ChrisMM** [git-town/git-town#3002]
When I'm reading through commits, I want an easy way to quickly distinguish them, so their purpose is clear.
* https://github.com/git-town/git-town/commits/main/

**Provided it's not cumbersome during development:**

When other contributors are making changes, I want them to easily prefix their commits using Conventional Commits, so they distinguish the purpose of the commit.

**Resources**
* https://commitizen.github.io/cz-cli/
* https://www.conventionalcommits.org/en/v1.0.0/
* https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional

**Conventional Commits**
```
feat:
fix:
build:
chore:
ci:
docs:
perf:
refactor:
revert:
style:
test:
```

**Impacts**
* https://github.com/git-town/git-town/blob/main/DEVELOPMENT.md

**Possible benefits with Golang:**
* https://goangle.medium.com/golang-improving-your-go-project-with-pre-commit-hooks-a265fad0e02f
* https://github.com/llorllale/go-gitlint

**Comment by kevgo** [comment]
Hey Chris!! 👋 Semantic commits are definitely not a bad idea and we have thought about doing them a number of times over the years.

Most people use them to generate release notes automatically. At Git Town we hand-craft our release notes to make sure they are informative and read well. Also to evaluate the level of changes (breaking or not). This determines the digit we need to bump on the release (major vs minor). 

It would have been nice to do semantic commits from the beginning to get statistics about how many bugfixes and refactorings we do. I suspect Git Town has now way over 50% refactorings, given that the project grew to a sizeable Bash/Ruby codebase that was then migrated over to Go. This required substantial re-architecting along the way and it would be nice to have some stats for it!

**Comment by ChrisMM** [comment]
Hola Kevin, It's always refreshing to instantly see your ability to recognize and value quality in process, when it makes sense (i.e. when it's not process for process sake!).

With the delimiter of a colon after the prefix'ed type of a commit and perhaps some further descriptor, the value of what was happening/change\d, how much work was involved (code churn?, line count?, ... ?), and how many times this occurs with the code file (history) and/or code base is then made available to analyze, like a in a review or retrospective, for potential improvements and commentary/questions.

Glad to help, if it helps, the Git Town project ... the use of Git Town came up as possibility in the toolchain of development with a company and, for them, it might be useful to know what has been changed and why, if they use it.

Hence: this issue submission.

Like with bug fixes, instead of wholly starting over or requiring incredible habitual changes, we can start implementing unit and other tests as required for a merge, and in the same way, we can start using conventional commits acknowledging that a previous set of commits data are not analyze'able as such, but the benefit going forward is worth the time / utilzation.

And, the benefit and adoption comes down to the Engineers' perspective of the advantages.

Any questions or experiences, just let me know please. Thank you

**Comment by kevgo** [comment]
Great to hear that there is interest from a company in Git Town. Please let me know if I can help answer any questions. Or if there are missing features that prevent adoption.

I don't expect end users to look at individual commits since there are often hundreds of commits in each release. Many of them are boring maintenance and cleanup or internal changes to the virtual machine powering Git Town. The [changelog](https://github.com/git-town/git-town/blob/main/CHANGELOG.md) summarizes the changes that end users need to be aware of in a human-friendly format. 

Said another way, in my opinion the information carried by conventional commits are for the internal developers, quality control, and product/project managers of a product, not its users.

Not sure if you refer to Git Town or another project around testing. For what it's worth, I'm pretty proud of Git Town comprehensive testing suite. Check out [this beauty](https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/merge_sync_strategy/edge_cases/conflict_feature_branch_main_branch_local_branch.feature) as an example for a full end-to-end test. I think you'll get a kick out of it! It creates a local and a remote Git repo, creates branches and commits, calls Git Town via the CLI, and verifies the resulting state of the local and remote repo. We have 289 such end-to-end tests. CI runs them on Linux and Windows. They cover pretty much all the functionality. Thanks to our highly tuned test infrastructure, the entire test suite run (highly concurrently) in about 25 seconds! At least on decent hardware like a MacBook with Asahi Linux. I have seen Git Town's test suite referenced in the wild as an example for a well implemented Cucumber test suite, aka human-readable end-to-end tests that allow cross-functional collaboration amongst the three-amigos (product, testing, development).

We also have comprehensive unit tests of course.

**Comment by ChrisMM** [comment]
Comprehensive unit tests, of course, and excellent documentation via features. 😄 

That is a [beauty](https://github.com/git-town/git-town/blob/main/features/sync/current_branch/feature_branch/merge_sync_strategy/edge_cases/conflict_feature_branch_main_branch_local_branch.feature)! The background and consequent scenarios could be enough content to present to a class alone. Thank you for sharing.

(Still wondering if anyone ever uses the [But for steps](https://cucumber.io/docs/gherkin/reference/)?)

Yes, the [changelog](https://github.com/git-town/git-town/blob/main/CHANGELOG.md) does an excellent job providing the list of changes, and in a human-friendly format. Very useful.

**Agreed**: "Said another way, in my opinion the information carried by conventional commits are for the internal developers, quality control, and product/project managers of a product, not its users."

Thank you for the time, feedback, and consideration.

**Comment by kevgo** [comment]
I think the word "but" in itself is an anti-pattern, and it's almost always better to use "and" instead. 

Example: 

1. "I'm a big fan of electronic music BUT this song sounds like random noise to me."
2. "I'm a big fan of electronic music AND this song sounds like random noise to me."

I think (2) is more correct because it communicates better that both parts of the sentence are true at the same time: I am a fan of electronic music, and while enjoying electronic music I don't enjoy this particular song.

Other example:

1. "I support you BUT this seems like a bad idea to me."
2. "I support you AND this seems like a bad idea to me."

(2) says the same things, and is more powerful. Both parts of the sentence work together and amplify each other, instead of working against each other. In sentence (1), the second part sounds like it (somewhat) invalidates the first part.

In the same reign, `But` almost never makes sense in Gherkin scenarios. Each step in a scenario is true independent of how the other steps look like.

**Comment by kevgo** [comment]
Agree. I have been using Cucumber for over 10 years now, on many projects. I have advised many clients, including pretty large and many small companies on it. Here on Git Town we push Gherkin pretty extensively and even embed other scripting and semantics into it. See the `{{ sha `branchname` }}` embeddings [here](https://github.com/git-town/git-town/blob/5e5e2f6bc754180dd38595f53936095f6d425525/features/sync/current_branch/feature_branch/merge_sync_strategy/sync_current_feature_branch_using_merge.feature#L42-L43), which get replaced at runtime with the addresses of commits. Never have I needed `But`. I guess it's in Gherkin mostly for the sake of completeness.
