### ISSUE TITLE
New branch selector UI breaks with a lot of branches

### ISSUE THREAD

**Issue by ruudk** [git-town/git-town#3119]
I'm on 12.0.1 and I did a `git sync` on an unknown branch. It asked me to select the parent.

I noticed the UI changed, but it breaks:
![Screenshot 2024-02-13 at 12 21 10@2x](https://github.com/git-town/git-town/assets/104180/33e2a998-bf3b-4d29-aaad-e1ecca32207b)

As you can see, I have a lot of branches, but the top of the UI is gone.

If I scroll up, I don't see it.

If I use Arrow UP to navigate, it does show the triangle move upwards, until it reaches the top (branch 36), and then nothing happens.

Also when I type `main`, nothing happens.

I'm on macOS using iTerm2.

**Comment by kevgo** [comment]
Thanks for reporting this. Yes, the UI is currently missing support for scrolling. I wanted to wait until somebody actually has so many local branches before building this. 

A fix is coming soon. 

Just out of curiosity, why do you have so many local branches?

**Comment by ruudk** [comment]
I have so many old branches, because they are old experiments. I go back there from time to time, and remove a few when no longer needed. So it just happens that I've kept a few experiments per month for the past years :) That adds up. Luckily, my git client collapses them into folders so I rarely see them.

**Comment by kevgo** [comment]
Interesting, thanks for sharing 🙏

Possible workarounds until this is properly fixed:

- Temporarily reduce the font size of your terminal so that all entries fit in your terminal window and you can select the right one. Most terminals have hotkeys like `ctrl`-`shift`-`minus` for this. After selecting the branch, you would restore the regular font size with `ctrl`-`shift`-`plus`.
- The main development branch is preselected in the dialog. If that's the parent you want to select, you could just hit `enter` without seeing the selection.
- Hit `esc` or `ctrl-c` to abort the dialog and run [git town set-parent](https://www.git-town.com/commands/set-parent).

I'm sure you know all this. Just listing this here in case somebody else runs into the same problem.

**Comment by ruudk** [comment]
> The main development branch is preselected in the dialog. If that's the parent you want to select, you could just hit enter without seeing the selection.

This is good to know! Will try that next time, thanks! 

💙 Git Town btw!

**Comment by kevgo** [comment]
This is implemented in #3120, #3121, #3125, and #3126.

**Comment by kevgo** [comment]
Please update to [v12.0.2](https://github.com/git-town/git-town/releases/tag/v12.0.2) for pagination support in dialogs.

**Comment by ruudk** [comment]
Just tested it out, it works perfectly! Thank you so much!

**Comment by kevgo** [comment]
In case you missed it: cursor left/right or `u`/`d` paginates 10 lines up/down.
