### ISSUE TITLE
`git town stack-depth`: prevent testing deeply nested branches on CI

### ISSUE THREAD

**Issue by kevgo** [git-town/git-town#3180]
### problem

- CI runs on every commit for every branch
- nested branches aren't being shipped anytime soon, so there is no point in spending CI cycles testing them
- It would be nice if Git Town could give the CI server hints how close a branch is to being shipped.
  - deeply nested branches that won't get shipped for a while don't get tested or get tested only quickly using integration and smoke tests
  - branches that are getting closer to being shipped get tested using the full test suite

### solution

- The CI server runs `git town branch-depth`. The command returns the depth of the branch as its exit code.
  - exit code 0 = this is a top-level feature branch, it is 0 steps away from being shippable
  - exit code 1 = this branch is 1 step away from being shippable because it has one feature branch as its parent
  - exit code 2 = this branch is 2 steps away from being shippable because it has two feature branch parents
- armed with this knowledge, the logic on the CI server can decide which tests to run for this branch

### alternatives

- #999 requires no CI changes but can only turn testing on or off, and only by the people that use Git Town to sync branches. This ticket works for everybody no matter how they sync branches.

**Comment by kevgo** [comment]
This could help restrict CI testing to top-level branches that have an open pull request.

Open question: how does the CI server know the ancestry of a branch?

- it doesn't have local Git configuration
- it probably has an API token configured, so it might be able to query the hosting API

**Comment by stephenwade** [comment]
If CI minutes are the motivation, it might be a better idea to just configure CI differently. My work uses the following configuration in our GitHub Actions workflows:

```yaml
on:
  pull_request:
    branches:
      - main
```

This configures the workflow to only run on commits to PRs against the `main` branch – thus, only PRs that are shippable, as PRs deeper in the tree will be against their parent branch instead of against the `main` branch.

I would be surprised if any CI provider didn't have a similar configuration option to only run against certain PRs.

**Comment by kevgo** [comment]
Good point that this is out of scope and should be addressed at the CI level. Closing this ticket.
