### ISSUE TITLE
`gt sync` suggestion: delete local branch first before syncing

### ISSUE THREAD

**Issue by tranhl** [git-town/git-town#3641]
### Your message to us

Currently, `gt sync` will:

1. pulls new commits for the current branch from its tracking and ancestor branches
2. downloads new Git tags
3. deletes the local branch if its tracking branch was deleted at the remote and the local branch doesn't contain unshipped changes
4. checks out the previously checked out Git branch in case the current branch got removed as part of the sync
5. local branches checked out in other Git worktrees don't get synced

My suggestion would be to do step 3 first. The reason for this is because step 1 can sometimes force us to resolve merge conflicts on a local branch that's already been shipped, which is unnecessary. Doing step 3 first will clean up the local branch, avoiding any unnecessary merge conflicts.

**Comment by kevgo** [comment]
Thanks for bringing this up! The documentation for this definitely needs improvement, so here is a more detailed explanation of why this works the way it does right now.

Merge conflicts are never fun, hence minimizing or eliminating them should always be a priority. To reduce the likelihood of conflicts, it's essential to keep your branches in sync as often as possible &mdash; ideally by syncing them dozens of times per day. To be able to sync one's branches so frequently, one must be able to sync at any time without thinking about it.

To allow being run without thinking, "git sync" needs to guarantee that it never accidentally loses any changes. To make this guarantee while deleting a local branch, "git sync" needs to prove first that the branch to be deleted contains no unshipped changes. Currently, Git Town verifies this by diffing the branch to delete against its parent branch. Only branches with an empty diff can be deleted safely. For this diff to potentially be empty, Git Town needs to sync the branch first, even if it's going to be deleted right afterwards.

Does this make sense so far?

I agree that it can be frustrating when "git sync" forces you to resolve merge conflicts only to delete the branch right after. 😆

A straightforward solution is to run "git sync --all" immediately after you've shipped/merged a branch. This way, the shipped branch isn't outdated and can be deleted without any merge conflicts. As a bonus, all your other local branches will receive the latest updates. 

Are there any specific reasons that prevent you from running "git sync" more frequently, especially after shipping/merging a feature branch?

**Comment by kevgo** [comment]
I have updated the documentation to explain this better in #3642.

**Comment by stephenwade** [comment]
> Are there any specific reasons that prevent you from running "git sync" more frequently, especially after shipping/merging a feature branch?

I'm not the OP, but my reason for not using `git sync` more frequently is that I don't want to push branches until I'm ready to propose. This is for two reasons:

1. I don't want to use CI minutes for branches I'm not done with (private repo so it costs my organization money)
2. I don't want all my coworkers to see "[branch] had recent pushes" banners whenever I start work on a new branch

My mental expectation of `git sync` is that it would rebase my local branch on top of the latest changes from `main` without pushing any branches that I haven't `git propose`d yet.

Related: https://github.com/git-town/git-town/issues/3511#issuecomment-2168966718

**Comment by kevgo** [comment]
@stephenwade thanks for sharing your workflow! I have created #3646 for discussing your idea of local-only feature branches.

**Comment by tranhl** [comment]
> Thanks for bringing this up! The documentation for this definitely needs improvement, so here is a more detailed explanation of why this works the way it does right now.

I appreciate the detailed explanation here! It really helps explain the constraints that `sync` needs to work within.

> Are there any specific reasons that prevent you from running "git sync" more frequently, especially after shipping/merging a feature branch?

In my particular case the conflicts come up when I either 1. forget to `git sync` after merging & the branch becomes stale, or 2. another team member sneaks in a change to the same code area and creates a conflict for me locally.

What if in the case of a diff between local & remote, `git sync` provides the ability to either continue syncing or delete the local branch via a prompt? The default could be set to "no" so that deleting the branch is an explicit action.

**Comment by kevgo** [comment]
> What if in the case of a diff between local & remote, git sync provides the ability to either continue syncing or delete the local branch via a prompt? The default could be set to "no" so that deleting the branch is an explicit action.

I like this idea!

Until this is built, if you know that you want to delete a branch, just accept "their" version for all merge conflicts. On the CLI this is something like `git checkout --theirs directory_name/*`. This resolves all merge conflicts for you by picking the version from the main branch. The result should be an empty feature branch which will then get deleted for you.

**Comment by kevgo** [comment]
If running `git checkout --theirs` is useful here, Git Town could offer to run it for you so that there is still some level of checking for unmerged changes.

**Comment by kevgo** [comment]
> What if in the case of a diff between local & remote, git sync provides the ability to either continue syncing or delete the local branch via a prompt? The default could be set to "no" so that deleting the branch is an explicit action.

Unfortunately there is no tracking branch to compare to since in this scenario the tracking branch was deleted at the remote.

I am also running into unnecessary merge conflicts often enough that they are annoying enough to do something about it. On the other hand, I would also find a dialog on every deleted branch annoying.

Possible idea to minimize distractions:

- Always sync branches whose remote is gone (as Git Town already does).
- If the sync goes through without a merge conflict and the branch is empty now --> delete (as Git Town already does).
- If the sync encounters a merge conflict --> show a dialog asking the user whether they want to do a safe delete (resolve the merge conflicts, then delete the branch if it is empty) or a quick delete (just delete the branch right now without checking for unshipped changes).
  - if the user chooses quick delete --> Git Town aborts the ongoing merge/rebase and deletes the branch
  - if the user chooses safe delete --> current behavior (let them resolve the merge conflicts, run `git town continue`, and then Git Town deletes the branch if it is empty)

**Comment by tranhl** [comment]
> On the other hand, I would also find a dialog on every deleted branch annoying.

@kevgo I second that, the less prompting we have to do the better.

The ideas you suggested are good, but my gut is telling me that perhaps `gt sync` is handling too many responsibilities 🤔. What if we offloaded the responsibility of deleting local branches to `gt ship` instead? This tracks in my mental model since deleting local branches is something I'm looking to do immediately after shipping a change. Thoughts?

**Comment by kevgo** [comment]
Thanks for diving into the search for the right abstractions here! 🙏 This is indeed a complex area with many interrelated factors. There's definitely merit to the idea of offloading local branch deletion to `gt ship`, as it semantically aligns with the concept of cleaning up branches that have already been shipped. We actually explored this idea in #1209. Historically, we had a dedicated `gt prune-branches` command for this, which was eventually merged into `gt sync` with [Git Town 10](https://github.com/git-town/git-town/releases/tag/v10.0.0). Here's the reasoning behind that decision.

Even if we added branch cleanup to `gt ship` or a `prune-branches` command, it wouldn’t fully address the issue raised in this ticket. Both options would still need to handle unshipped local changes to avoid silently losing work.

Moreover, not all branches deleted on the remote were shipped-—PRs get closed and branches get deleted for various reasons. Cleaning up those branches via `gt ship` feels counterintuitive since they were never shipped in the first place. On the other hand, using `gt sync` to remove these branches makes more sense, as it keeps the local environment in sync with the remote repo, reflecting any branch deletions and syncing commits across all branches.

For observed or contribution branches, I - the observer or contributor - shouldn't be responsible for shipping them-—that is not my role. Running `gt ship` to clean up those branches even if they get shipped would be conceptually wrong.

If `gt sync` doesn’t remove branches whose remotes are gone, what should it do? Prompt the user to run `gt ship`? That would be a poor user experience, as the system already knows what to do. Run `gt ship` automatically? That’s essentially what we do now.

Adding a separate `shipped` or `prune-branches` command would add yet another command users need to remember to run regularly, alongside `gt sync`. Otherwise, they'd end up with a cluttered workspace full of shipped branches.

Even if we introduced a `gt shipped` command or enhanced `gt ship` to handle cleanup, you'd still need to run `gt sync` afterward to pull the shipped commits into your feature branches. This indicates that branch cleanup is logically part of the sync process.

**Comment by sergej-koscejev** [comment]
Can Git Town analyze the current state before it runs `git fetch` as part of `gt sync`? In particular, it could note which branches have local commits compared to remotes.

If such a branch is deleted during fetch, it should be simply deleted locally. (Maybe keep a log of such deleted branches somewhere, in case it turns out that the user wanted to preserve the changes locally. But perhaps git reflog is enough.)

Otherwise I have a situation where my branch was squash-merged on GitHub but when I run `gt sync` it wants me to do the nonsense work of resolving conflicts between individual non-squashed commits (because I use the rebase sync strategy). Apart from being confusing, it seems to be completely unnecessary because the branch is going to be deleted anyway IIUC.

**Comment by kevgo** [comment]
I like your idea to check the local repository state before running `git fetch`. This sounds like a reliable way to determine whether local branches have unpushed commits. Which addresses the key blocker for improving the user experience in this area. Quite a brilliant solution. Thanks for the thoughtful contribution!

**Comment by kevgo** [comment]
This is now shipped as [Git Town 16.5](https://github.com/git-town/git-town/releases/tag/v16.5.0).
