### ISSUE TITLE
`git hack` fail if main branch is missing

### ISSUE THREAD

**Issue by FirelightFlagboy** [git-town/git-town#3703]
### Steps to reproduce

1. Have a git repository with a main branch
2. Create a new feature branch `random-branch-1`
3. Remove the main branch

   ```shell
   git branch -D $main_git_branch
   ```

4. Create a new feature branch `new-feat-2`
 
   ```shell
   git town hack new-feat-2
   ```

### Command output

```shell
[random-branch-1] git fetch --prune --tags
[redacted]

Error: there is no branch "master"
```

### Additional information

I would have expected that `git-town` to be able to recover from that error.

`git-town` could create the branch using `$remote/$main_git_branch` over the local `$main_git_branch`

**Comment by kevgo** [comment]
Beautiful edge case, thanks for reporting this! 🙏 

This will get fixed in the way you describe. Just out of curiosity, do you have a real-life scenario where somebody doesn't have the main branch checked out locally?

This has made me wonder whether `git sync` should or should not change which branches exist locally: https://github.com/git-town/git-town/issues/3769.

**Comment by FirelightFlagboy** [comment]
Sometimes I remove the main branch to simplify using 

```shell
git push origin '+:'
``` 

That command push all branches that are not in sync with the remote (useful after a rebase using `--update-refs` with stacked branches), that also include the main branch.
So before doing that command I would either switch to the main branch to sync it or just remove it.
