### ISSUE TITLE
"git town branch" command

### ISSUE THREAD

**Issue by zodman** [git-town/git-town#3807]
### Your message to us

Show branches linage is something that should be separate from git-town config...

it's very useful!!!

**Comment by kevgo** [comment]
You can run `git town switch` to see only the lineage (and change branches while you look at it).

If this doesn't work for you, what's your use case for seeing the lineage?

**Comment by zodman** [comment]
its just display the lineage, not  action should be executed ...

**Comment by kevgo** [comment]
What do you need the lineage information for, and in which data format?

**Comment by zodman** [comment]
it just for show whats the parent and child ..  i had to many 1-XXXX and 2-XXX I don't know which own to which ...

**Comment by kevgo** [comment]
This sounds like a one-off situation. Why can't you use the output of `git town config` for this?

**Comment by kevgo** [comment]
Thanks, the `git town config` command showing the API key is a good argument against it. Definitely open to a `git-town ls` or `git-town branch` command. Can you pls give a specific example for the output that you would expect from such a command? What information would it display? All branches? Only the children of a particular branch? Would the output be JSON, TSV, or plain text?

**Comment by stephenwade** [comment]
I would expect it to display all branches, in plain text format. It could also be expanded to show only branches related to a particular branch based on a command-line parameter.

My suggestion would be:

1. Add branch type information to `git town switch` (so you can get the same information in that command)
2. Use the same nicely colored output from `git town switch` as the output for `git town ls`

Here's some example output:

<img width="317" alt="Screenshot 2024-09-04 at 5 59 44 PM" src="https://github.com/user-attachments/assets/1be0ca34-56ed-4d99-be23-1d0e7d60f8cf">

**Comment by kevgo** [comment]
Love that screenshot draft, thanks! 🙌

**Comment by kevgo** [comment]
Considering the similarities in content and output with the `git branch` command, what do you think about naming this command `git town branch`?

I also like the idea of adding the branch type to the `git town switch` command, and have created https://github.com/git-town/git-town/issues/3937 to track that idea.

**Comment by stephenwade** [comment]
`git town branch` makes sense to me!

**Comment by kevgo** [comment]
@stephenwade @zodman please help me think through this new feature.

Assuming `git town switch` gets changed this way:

- it also displays the branch types, similar to the screenshot @stephenwade made above
- it no longer removes the branch list when it ends, i.e. the branch list remains visible after the program ends
- you can increase the number of branches displayed at a time, e.g. tell it to display 30 branches instead of 10 branches at a time

If all that is in place, would you be able to use `git town switch` instead of a new `git town branches` command?

I'm asking because introducing a new top-level command is a big deal. It needs to be documented, and all Git Town users need to learn about it. I want to make sure this new command is useful for enough people to justify the additional learning curve and complexity.

Can you please outline specific use cases in which you would need the hypothetical `git town branches` command?

**Comment by stephenwade** [comment]
> If all that is in place, would you be able to use `git town switch` instead of a new `git town branches` command?

(nitpick: If the command is created, it should be named `git town branch` not `git town branches` for consistency with `git branch`.)

Yes. But…

> Can you please outline specific use cases in which you would need the hypothetical `git town branches` command?

I would prefer to have a separate `git town branch` that I can alias to `git ls` (otherwise, using it in the way I want will always mean pressing Ctrl-C).

I also can't think of any case where I want `git town switch` to change the number of branches it displays, whereas I always want `git branch` to show me everything. Adding a option to increase the number of branches displayed at a time seems like it would only be used in this use case.

For these reasons, even though the output is similar, I feel that they should be two separate commands.

**Comment by kevgo** [comment]
Thanks, that's helpful. Thinking more about it, I'm starting to see it the same way.

**Comment by kevgo** [comment]
This is now available as part of [Git Town 16.2](https://github.com/git-town/git-town/releases/tag/v16.2.0). Enjoy!

**Comment by kevgo** [comment]
@zodman @stephenwade I’m now using the new `git town branch` command multiple times a day, and it’s incredibly useful. It gives me a quick overview of my current position in the repo and the other branches that exist. I’ve even aliased it to br in my shell. Thanks for coming up with this idea and taking the time to explain it!
