### ISSUE TITLE
Add option to avoid syncing on `git town append` and `git town propose`

### ISSUE THREAD

**Issue by ianjsikes** [git-town/git-town#4059]
### Your message to us

The `--detached` flag was recently added to `git sync`, which is really amazing for my use case (frequently using stacked branches in a repo with a _lot_ of activity on the main branch). This will let me quickly jump around between stacked branches and keep them all up to date while avoiding a lot of unnecessary pushes (CI triggers, etc).

My main issue now is that `git town append` and `git town propose` _also_ seem to implicitly run a `git town sync`, except this flag isn't exposed in these commands. So if I want to make a 3-deep stack of PRs, I:
- Create the first PR with `git town hack branchA`. This causes a full sync, which is acceptable IMO. I generally always want to be branching off of `main` with the latest version on the remote.
- Make and commit some changes.
- Make a new branch with `git town append branchB`. This updates `main`, checks out `branchA`, updates it and pushes up the changes, then makes the new branch. I'd rather not do the update from `main` at all.
- Make and commit some changes.
- Make a new branch with `git town append branchC`. This updates `main`, checks out `branchB`, updates it and pushes up the changes, checks out `branchC`, updates it and pushes up the changes, then makes the new branch. The *two* unnecessary pushes is extra painful.

What I'd really love is some config option I can set that totally disables syncing stacked branches with changes from the main branch (making _all_ of these commands work similar to how the `--detached` flag works)

**Comment by kevgo** [comment]
I agree. At a minimum, the `append`, `prepend`, and `propose` command should get a `--detached` option.

Please note that if you have uncommitted changes while running `git town append` or `prepend`, these commands already don't sync, so that you can commit your open changes first. This is not exactly the behavior you ask for in this ticket, but maybe a workaround until the `--detached` flag ships for the commands listed above.

Assuming there would be an "always be detached" option for Git Town, which makes all commands run in detached mode. When and how would you want to pull in changes from the main branch in this scenario?

We tried removing the syncing of branches from the `propose` command a few months ago. Unfortunately, we ran into a lot of edge cases, so that we decided to keep syncing for now: https://github.com/git-town/git-town/issues/3632#issuecomment-2258411899. The `--detached` option seems more workable than removing syncing altogether. Thanks for the suggestion!

**Comment by kevgo** [comment]
Thanks for taking the time to write this down. I see the broader pattern you're aiming for, and I agree that adding a config option to prevent `append` and `prepend` from pulling external updates could be somewhat useful for busy monorepos.

A concern is that the behavior of `git sync` is now different depending on properties of the parent branch. In your example, when I run `git sync` on `branchA`, which is a feature branch, it pulls updates from main. But if I run the same command on `branchB`, which is also a feature branch, then it doesn't. I think this would confuse most people who expect consistent behavior across the same branch type.

I can also foresee that other people prefer slightly different behaviors, and then there are endless config options and people are still left wanting better support for their specific situation.

I therefore think it's best to give people an easy way to create their own custom commands. The upcoming Git Town 16.4 will introduce `--detached` options to `hack`, `append`, `prepend`, and `propose`. Combined with the existing `--detached` option for `sync`, this should allow you to create your own custom command shortcuts ("gts" for "git town sync --detached") or Git aliases ("git dsync") that do exactly what you want. Would this work for you?

**Comment by ianjsikes** [comment]
Yeah, making my own aliases with these flags works perfectly for my case. Thanks for the thoughtful response 😄

**Comment by kevgo** [comment]
Just an update on this. There is now a `--detached` flag for all Git Town commands, and since [v20.2](https://github.com/git-town/git-town/releases/tag/v20.2.0) it doesn't pull in any updates from the local main branch.
