### ISSUE TITLE
synchronizing all descendants before shipping a parent branch

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#764]
When shipping a parent branch, I think we should ensure all descendant branches are up to date. This helps avoid conflicts when syncing the child branch with master after the parent is shipped.

**Comment by kevgo** [comment]
Possible ways to go about this:
1. display an error and abort the ship
2. display a warning and continue the ship after user confirmation
3. automatically perform a `git sync --all` instead of a simple `git sync` when shipping

My vote goes to (2), since it is the most compatible with different environments.

**Comment by kevgo** [comment]
Thinking about this more, and given that we already sync the current branch when shipping, I agree with the original idea that we should also sync all descendent branches when shipping. Then sync them again right after shipping. This way we can automatically resolve any false merge conflicts we encounter by running `git checkout --theirs <branchname>`. This solves a big headache with squash merging, and the biggest reason why some people favor normal merging over it!

**Comment by kevgo** [comment]
This puts a lot of pressure on the CI server, so should be configurable.

**Comment by kevgo** [comment]
merging this idea into #3841
