### ISSUE TITLE
change directory

### ISSUE THREAD

**Issue by charlierudolph** [git-town/git-town#957]
When we change the directory in Go, it does not change the directory of the calling process. Thus if the folder you start in disappears during the process of running a command you end up in an invalid directory. 

See this [branch](https://github.com/Originate/git-town/compare/cr-fixCd?expand=1) for updates that cause test failures. We weren't properly saving what the directory is that the process finished in

**Comment by kevgo** [comment]
We have [tests for this case](https://github.com/Originate/git-town/blob/master/features/git-town-sync/folder_does_not_exist_on_main_branch/no_conflict.feature) already. How do they pass when this is still an issue?

**Comment by charlierudolph** [comment]
I believe  we were changing the directory after the command finished running without inspecting the final working directory.

**Comment by kevgo** [comment]
E2E test to reproduce the buggy behavior:

- create and checkout a feature branch `feature`
- create a folder and file in that branch
- run `git kill` on that branch
- expected: the shell is now in the root folder (how could it get there?)

**Comment by kevgo** [comment]
I don't think there is a way to prevent this. Shells are intentionally not letting scripts change the current directory because that would be a security issue. To avoid this, one would have to call Git Town from a shell wrapper, similar to how [mrt](https://github.com/kevgo/multi-repo-tool/blob/main/documentation/install.md) does it. More info: https://unix.stackexchange.com/questions/27139/script-to-change-current-directory-cd-pwd
